### ISSUE TITLE
the same attribute has different data type in different methods

### ISSUE THREAD

**Issue by gaterslebenchen** [plantbreeding/API#107]
for example, the data type of attribute "studyDbId" is String in "phenotypes-search", but it is Number in "studies-search" method; the data type of attribute "plotNumber" is String in "phenotypes-search", but it is Number in "Retrieve sample metadata " method.

**Comment by lukasmueller** [comment]
Thank you for noting the discrepancy. The correct type for DbId is (url-encoded) string. We'll fix this asap.
