### ISSUE TITLE
Pagination problems

### ISSUE THREAD

**Issue by mverouden** [plantbreeding/API#118]
Dear all,

I also posted a message on the slack channel today. Why does currentPage in the pagination start with 0 instead of 1? To me this is totally contra intuitive and apparently I am not the only one. Different databases have implemented this differently. I came across this while adapting the BrAPI R implementation to work with BMS and also checking it against BTI-bases, and others.

To make a long story short pagination and especially the specification for the page in the call should be uniformly defined. I would opt for calling the first page nr 1 instead of 0 and therefore, the currentPage to start at 1 also. If you call with pageSize = 10 and the totalCount = 50, there should be 5 pages (page 1 to 5).

Awaiting your response to this issue,

With kind regards,

**Comment by imilne** [comment]
We've already had this discussion though - multiple times. 0 was decided upon, and also documented in the specification.

**Comment by mverouden** [comment]
Ian provided me with an answer, that explains it all. I, therefore, have closed the issue myself.

**Comment by nahuel-soldevilla** [comment]
Hello @mverouden  and @imilne 
I'm interested in this topic. Do we have any records of why this convention was agreed upon?

Thanks!
