### ISSUE TITLE
Missing GET method in /phenotype-search

### ISSUE THREAD

**Issue by martinbaste** [plantbreeding/API#129]
The standard method for this resource would be GET, as we are fetching information given some parameters.
I understand the POST method is useful/required for queries with a long list of parameters, but why is there no GET method in [/phenotype-search](https://github.com/plantbreeding/API/blob/master/Specification/Phenotypes/PhenotypeSearch.md)?

**Comment by BrapiCoordinatorSelby** [comment]
related to discussion in #191
