### ISSUE TITLE
crop vs speciesId

### ISSUE THREAD

**Issue by GuilhemSempere** [plantbreeding/API#130]
/maps supports a parameter named species

Unless I'm wrong, the only way we can get a value to pass there is by using the /crops call.

... shouldn't both names be harmonized?

**Comment by homonecloco** [comment]
What about Brassica rapa (https://en.wikipedia.org/wiki/Brassica_rapa)?. Which is a single species that provides several crops...

**Comment by GuilhemSempere** [comment]
The problem is getting worse then...

**Comment by BrapiCoordinatorSelby** [comment]
NOTE: as of V1.2 `crops` have been replaced with `commonCropNames`

few options I see to solve this. 
A) Remove `species` from the Map object and call
B) Replace `species` with  `commonCropName`, found by /commoncropnames
C) Connect the Map object to Germplasm with a germplasmDbId
D) Add full taxonomy reference to Map object

Thoughts?

**Comment by homonecloco** [comment]
I would probably have: 

```commonCropName```
and then have also the 
```scientificName``` 
of the species, that way there is no ambiguity (hopefully...)

In that way you can still refer by the crop name, but you have on the back the actual species. So you can have all the Yams with the same crop name, but the underlying scientific name will be different. This also allows to have _Brassica oleracea_ in the scientific name, and in the crup have ```Broccoli|Brussels sprouts|etc````

**Comment by mverouden** [comment]
@BrapiCoordinatorSelby I am in favor of this idea. It makes perfect sense to keep a commonCropName as well as a scientificName as suggested by @homonecloco. Can also recommend to add this addition to the commonCropNames call. It would anchor this call better into BrAPI as well.

**Comment by GuilhemSempere** [comment]
Fine for me
