### ISSUE TITLE
Using AND and/or OR conjuctive operators in search calls

### ISSUE THREAD

**Issue by nikkicarumba** [plantbreeding/API#14]
There is no description in the search calls how to combine multiple condition in the query.

Using the request body in [studies-search](http://docs.brapi.apiary.io/#reference/0/search-studies/search-studies)
`{`
`   "studyType" : "Trial",`
`   "studyNames" : ["Study A", "StudyB"], `
`   "studyLocations" : ["Kenya", "Zimbabwe"], `
`   "programNames": ["Test Program", "Program2"],`
`   "germplasmDbIds" : [ "CML123", "CWL123"],`
`   "observationVariableDbIds": ["CO-PH-123", "Var-123"],`
`   "active" : "true",`
`   "sortBy" : "studyDbId",`
`   "sortOrder" : "desc"`
`}`
This can be translated into 2:
(1)
All these parameters can be combine using OR in the SELECT query. The result will be all studies with studyType=trial and all studies with name Study A and StudyB and all studies with studyLocatiios Kenya and Zimbabwe....
`studyType=Trial OR`
`studyName=Study A OR studyName=StudyB OR`
`studyLocation=Kenya OR studyLocation=Zimbabwe OR`
`programName=Test Program OR programName=Program2 OR`
`germaplasmDbId=CML123 OR germaplasmDbId=CML124 OR`
`observationVariableDbId = CO-PH-123 OR observationVariableDbId=Var-123 OR`
`active=true`

(2)
if we use OR for variables with several values, and use AND operator to combine the conditions above would be translated into this partial query:
`studyType=Trial AND`
`(studyName=Study A OR studyName=StudyB) AND`
`(studyLocation=Kenya OR studyLocation=Zimbabwe) AND`
`(programName=Test Program OR programName=Program2) AND`
(germaplasmDbId=CML123 OR germaplasmDbId=CML124) AND
(observationVariableDbId = CO-PH-123 OR observationVariableDbId=Var-123) AND
active=true

I would suggest the latter, what do you all think?

**Comment by jackeblagare** [comment]
Logically, it would be AND. Specifying a particular value is an implication that I want to find a record having this particular attribute.

**Comment by jeback1** [comment]
Hi Nikki,
I agree with Jack that the way it is currently defined, having multiple parameters would behave as AND.  To achieve OR, you would need to make multiple calls.  To extend the API to support OR logic in the parameter list would need to be a new feature that would need to be considered for version 2.  If you think it would be a valuable addition, please open a new issue and assign the milestone to be version 2.

Best regards,
Jan Erik
