### ISSUE TITLE
Pedigree call does not contain information about female/male parentage.

### ISSUE THREAD

**Issue by dauglyon** [plantbreeding/API#150]
In the pedigree call (https://github.com/plantbreeding/API/blob/master/Specification/Germplasm/GermplasmPedigree.md) it seems there should be information returned on whether a parent is the female or male parent.

**Comment by dauglyon** [comment]
This might be enforced by the convention around the `pedigree` string (e.g. female first), but it does not appear to be explicitly documented.

**Comment by cpommier** [comment]
We curently have the following object/return available for each germplasm : 
```

"children": [
      {
        "crossingPlan": "string",
        "crossingYear": "string",
        "familyCode": "string",
        "firstParentName": "string",
        "firstParentPUI": "string",
        "firstParentType": "string",
        "secondParentName": "string",
        "secondParentPUI": "string",
        "secondParentType": "string",
        "sibblings": [
          {
            "name": "string",
            "pui": "string",
            "value": "string"
          }
        ]
      }
    ],
```

**Comment by BrapiCoordinatorSelby** [comment]
Can someone give me an example of a "crossingPlan" and a "familyCode" please?
Also, what does "value" represent for a sibling?
