### ISSUE TITLE
Search Studies Get and Post | Duplicated attribute?

### ISSUE THREAD

**Issue by netbofia** [plantbreeding/API#159]
Hello I was looking at this example of the return for both the Search Study calls (POST and GET)
Is studyType repeated?
And if not what is their differences?
Arrows below pointing to the attributes in cause. 

Example of results for search study

          "data": [ 
              {
                  "studyDbId": "35",
                  "name": "Earlygenerationtesting",
                  "trialDbId" : "7",
                  "trialName" : "InternationalTrialA",
       ----->     "studyType": "Trial",
                  "seasons": ["2007 Spring", "2008 Fall"],
                  "locationDbId": "23",
                  "locationName": "Kenya",
                  "programDbId": "27",
                  "programName": "Drought Resistance Program A",
                  "startDate": "2007-06-01",
                  "endDate"  : "2008-12-31",
      ----->      "studyType": "Trial",
                  "active" : "true", 
                  "additionalInfo" : {
                      "property1Name" : "property1Value",
                      "property2Name" : "property2Value",
                      "property3Name" : "property3Value"
                  }
              }

**Comment by BrapiCoordinatorSelby** [comment]
Yup looks like a copy/paste error to me. Good catch!
