### ISSUE TITLE
Geodetic datum for locations

### ISSUE THREAD

**Issue by guignonv** [plantbreeding/API#164]
For the "locations/LocationDetails" call, we use latitude and longitude but we do not specify in which geodetic system while there are several standards. For people willing to display location on a map, this can lead to bad interpretation of location when comparing dat from different sources using different geodetic systems.

I suggest we should either add a field "geodeticDatum" to this call with a list of allowed values ("WGS84", "AGD84", "GDA94", "GRS80",...?), or specify in the documentation a standard we should all agree on that must be used to provide latitude and longitude coordinates, for instance "WGS84". I would vote for my second proposition unless we have people using other types of geodetic systems.

Resource: https://en.wikipedia.org/wiki/Geodetic_datum

**Comment by BrapiCoordinatorSelby** [comment]
Yes I would agree. It looks like GPS systems and Google Maps use WGS84, so it would make sense to standardize to that. I assume those are the 2 most common ways people use to find a locations coordinates.
