### ISSUE TITLE
Search default behavior when no params are given

### ISSUE THREAD

**Issue by martinbaste** [plantbreeding/API#167]
Maybe I missed it in the documentation, but is there a defined default behavior for all the -search endpoints when no parameters are given? I saw it mentioned in #90 that by default it returns all entries. It makes sense to have it as a way to explore the dataset.

If this is the case, I think it should be clearly specified in the documentation (again, it could be that I missed it), in the Search Services section.

**Comment by guignonv** [comment]
I didn't see it in the doc but I assumed all should be returned as the user didn't set any filter. But it could be explicitly written in the doc for sure with no cost. :-)

**Comment by BrapiCoordinatorSelby** [comment]
agreed
