### ISSUE TITLE
Consistency between study's germplasm and other germplasm calls

### ISSUE THREAD

**Issue by gcornut** [plantbreeding/API#169]
Should the [study germplasm details call](https://github.com/plantbreeding/API/blob/master/Specification/Studies/Studies_Germplasm_GET.md) just list germplasm in a study and have the same fields as in [germplasm details](https://github.com/plantbreeding/API/blob/master/Specification/Germplasm/GermplasmDetailsByGermplasmDbId.md) or [germplasm search](https://github.com/plantbreeding/API/blob/master/Specification/Germplasm/GermplasmSearchGET.md)?

Does anyone need the "entryNumber" field in the study germplasm call (which is absent from the other germplasm calls) ?

Edit: Do we really need the "studyDbId" and "trialName" in the study's germplasm response?

**Comment by c5sire** [comment]
If I recall right the "entryNumber" refers to a number often assigned during the design of a field trial. It helps keep track of the original randomization order.

**Comment by gcornut** [comment]
I see but the link between an entry and a germplasm is already present on the layout (study/id/layout) or on the observation unit (/study/id/observationunits or /phenotypes-search) so I'm not sure we need it here

**Comment by c5sire** [comment]
Indeed. Should only be present where it most naturally belongs - my take would be the study layout.
