### ISSUE TITLE
Usage of HATEOAS (or any other similar mechanism) in V2

### ISSUE THREAD

**Issue by rfinkers** [plantbreeding/API#17]

**Comment by gcornut** [comment]
Related to plantbreeding/API#7

**Comment by c5sire** [comment]
Indeed:

on a multicrop server: in the concept of REST architecture one should be able to get the next step from just looking at server calls. So, how do I know which crops to look for in the first call? One option: Can we assume an initial empty call for all brapi servers like: my.server.org/brapi/v1/crops which returns the list of all crops on that server and then one can go from there? E.g. assume the crops calls returns crop1, crop2, ... and then one knows that the crop specific calls are accessible via: my.server.org/crop1/brapi/v1/calls; my.server.org/crop2/brapi/v1/calls. In the case of a single crop server as before the 'crop' path element is omitted. To be more explicit: maybe the crop call should return corresponding links for each crop (like datalinks).

**Comment by c5sire** [comment]
Here a nice chapter on HATEOAS: https://leanpub.com/build-apis-you-wont-hate/read_sample

**Comment by BrapiCoordinatorSelby** [comment]
Closing issue in favor of #192 
JSON-LD has a data linking mechanism similar to HATEOAS, though a little more complex
