### ISSUE TITLE
Naming of identifiers in path

### ISSUE THREAD

**Issue by c5sire** [plantbreeding/API#173]
Should identifiers used as a resource locator in the url better be called *resource id* in the documentation and not listed as parameters? 
They are conceptually different from parameters.

**Comment by BrapiCoordinatorSelby** [comment]
Resource Ids contained within a URI are still variable parameters for a given call, but you are right they are a little different. Some libraries (Java Spring) refer to them as Path Parameters vs Query Parameters to make the difference clear. 

Unfortunately, within the documentation, Apiary only allows for one list of parameters and treats them all the same.

**Comment by BrapiCoordinatorSelby** [comment]
With the new OpenAPI definition format, call parameters have the `in` field which defines what type of parameter it is. 
`in: path` indicates it is a resource id in the path of a call
`in: query` indicates a query parameter used at the the end of a URL
`in: body` indicates a complex object which is the body of the request for POST and PUT calls
