### ISSUE TITLE
Duplicate call documentation for allelematrix-search

### ISSUE THREAD

**Issue by guignonv** [plantbreeding/API#174]
We got 2 documentation pages for the same call:

1. MarkerProfile Allele Matrix [/brapi/v1/allelematrix-search]
https://github.com/plantbreeding/API/blob/master/Specification/MarkerProfiles/MarkerProfileAlleleMatrix.md

2. Scores through POST [POST /brapi/v1/allelematrix-search]
https://github.com/plantbreeding/API/blob/master/Specification/MarkerProfiles/ScoresThroughPOST.md

The first one is for both POST and GET while the other is only for POST.
I think we should only keep the first one but I don't know why/how it got duplicated. Somebody has an idea? Was it just a little mistake?

**Comment by BrapiCoordinatorSelby** [comment]
I don't see any POST call in MarkerProfileAlleleMatrix.md? Am I missing something?
I'm trying to standardize on 1 call per file, so GET and POST for the same URI will be in different files.

**Comment by guignonv** [comment]
It's fine to have 2 files, one for GET and one for POST. Maybe the first file name should include "GET" then?
ie. https://github.com/plantbreeding/API/blob/master/Specification/MarkerProfiles/MarkerProfileAlleleMatrixGET.md
