### ISSUE TITLE
Call name consistency for allelematrix-search vs allelematrices ... and vendor/plate[s]-search

### ISSUE THREAD

**Issue by guignonv** [plantbreeding/API#175]
Here we got a call "/brapi/v1/allelematrices"
https://github.com/plantbreeding/API/blob/master/Specification/MarkerProfiles/AlleleMatrices.md

while there we got /brapi/v1/allelematrix-search
https://github.com/plantbreeding/API/blob/master/Specification/MarkerProfiles/MarkerProfileAlleleMatrix.md

Since we got:

- markers-search
- phenotypes-search
- programs-search
- samples-search
- studies-search
- variables-search

and so on, I think the call should be renamed "allelematrices-search" right?

**Comment by guignonv** [comment]
By the way, there is also the same type of issue for the call "vendor/plate-search" which should be "vendor/plates-search", isn't it?

https://github.com/plantbreeding/API/blob/master/Specification/ExternalVendorSamples/Vendor_PlateSearch_GET.md

https://github.com/plantbreeding/API/blob/master/Specification/ExternalVendorSamples/Vendor_PlateSearch_POST.md

**Comment by BrapiCoordinatorSelby** [comment]
Agree. everything should be standardized to plural nouns

**Comment by guignonv** [comment]
...and I forgot vendor/plate[s]/{vendorPlateDbId} as well but it was obvious. ;-)
https://github.com/plantbreeding/API/blob/master/Specification/ExternalVendorSamples/Vendor_Plate_GET.md

**Comment by guignonv** [comment]
Sorry again... and what about vendors with an "s" in those vendor* calls?

**Comment by BrapiCoordinatorSelby** [comment]
I'm torn about "vendors". 
It does break the rule of "everything plural". 
But it is there to denote a category of server implementation, not a data entity. I could argue that the full plural noun is "vendor plates" vs another type of "plates". 

...

Unless anyone has a strong feeling about this, I think I'm gonna bend the rule in this case. "vendor/plates" makes more intuitive sense to me. The intention is that these calls are implemented by a single vendor system.
