### ISSUE TITLE
Naming inconsistencies for search parameters in /germplasm-search POST-request

### ISSUE THREAD

**Issue by patrick-koenig** [plantbreeding/API#176]
The property keys of a germplasm result ( result of /germplasm or /germplasm-search ) does not matching the proposed names of the corresponding search parameters in the POST-request of /germplasm-search.

**Examples:**

Search parameter for searching by germplasmDbId is the plural "germplasmDbIds":

```
{
  "germplasmDbIds": [
    "986",
    "01BEL084609"
  ]
}
```

Corresponding property in the result set is singular "germplasmDbId".

---------

Search parameter for searching by accessionNumber is the plural "accessionNumbers":

```
{
  "accessionNumbers": [
    "ITC0609",
    "ITC0685"
  ]
}
```

Corresponding property in the result set is singular "accessionNumber".

---------

# **BUT:**

Search parameter for searching by genus is NOT the plural but instead "germplasmGenus":

```
{
  "germplasmGenus": [
    "Solanum",
    "Triticum"
  ]
}
```

**BUT** corresponding property in the result set is only "genus".

---------

It's the same for species:

```
{
  "germplasmSpecies": [
    "aestivum",
    "vinifera"
  ]
}
```

BUT corresponding property in the result set is only "species".

---------

# **CONCLUSION:**

Naming convention of the search parameters should always match the corresponding names in the results sets to avoid confusion and unneccessary raise of complexity of business logic on the implementation side.

**Comment by guignonv** [comment]
Agreed! +1
