### ISSUE TITLE
Replace call "variables/datatypes" by static documentation

### ISSUE THREAD

**Issue by guignonv** [plantbreeding/API#179]
https://github.com/plantbreeding/API/blob/master/Specification/ObservationVariables/VariableDataTypeList.md

The call variables/datatypes returns a list of supported data types for observation variables. The goal of such a call is to provide supported data types to clients and be not restrictive on the list of types supported by a given server. However, the allowed data type names are not specified in the documentation so what a server could call "categorical" could be called "classes" or "cvterm" or "list" by others. Then clients wouldn't be able to deal with these... as long as they are not documented. But then, if they are documented, there is no use of this call. A client would just receive an attribute value and its type without needing to know which data types are supported.

Proposal: this call should be removed and data types should juts be listed and put in the ObservationVariables documentation. Some of the type names we could use are defined in the crop ontology: Ordinal, Numerical, Time, Duration, Nominal, Categorical,...
We need someone to make an exhaustive list of data types with their definition... Marie Angélique? :)

**Comment by BrapiCoordinatorSelby** [comment]
@marieALaporte you have been called on!
I agree this set of data types should be documented and come from an ontology, it should not be left up to the implementer to decide their own data types.

**Comment by marieALaporte** [comment]
In the Crop Ontology project, we use the following types: http://www.cropontology.org/brapi/v1/variables/datatypes

The types are described in [our guidelines](http://www.cropontology.org/CropOntology_Curation_Guidelines_20160510.pdf) (page 8 and 9)

We are open to discuss to have more datatypes if needed
