### ISSUE TITLE
Rename /trails call to investigation to be MIAPPE (or other standard) compliant?

### ISSUE THREAD

**Issue by rfinkers** [plantbreeding/API#18]

**Comment by BrapiCoordinatorSelby** [comment]
@rfinkers Is this still relevant? I can't find "investigation" anywhere in the MIAPPE spec. And I couldn't find "investigation" in the Crop Ontology either. Can you send me the standard you are referencing here?

**Comment by rfinkers** [comment]
Investigation concept is connected to ISA-TAB data standard. Let's close this oen for now.
