### ISSUE TITLE
Document variable search parameters

### ISSUE THREAD

**Issue by gcornut** [plantbreeding/API#180]
The variable search parameters:
```json
{
      "page": 0,
      "pageSize": 2,
      "observationVariableDbIds" : ["obs-variable-id1", "obs-variable-id1"],
      "ontologyXrefs" : ["CO:123", "CO:456"],
      "ontologyDbIds" : ["CO_334:0100632"],
      "methodDbIds" : ["method-1", "method=2"],
      "scaleDbIds" : ["scale-1", "scale-2"],
      "names" : ["caro_spectro"],
      "datatypes" : ["numeric"],
      "traitClasses" : ["Phenological", "Physiological"]
  }
```
The "ontologyXrefs" parameter is not very clear. Should it filter variables by variable.xref or by variable.xref & trait.xref & scale.xref?

I can add documentation on these search parameters once this is more clear.
Also it would be nice to have better parameter value examples that actually appear in the response.

**Comment by BrapiCoordinatorSelby** [comment]
I'm not sure what the original intention was, but I think it would be helpful to change the "ontologyXrefs" search param with "variableXref", "traitXref", and "scaleXref" to be clear.
