### ISSUE TITLE
Germplasm Markerprofiles [/brapi/v1/germplasm/{germplasmDbId}/markerprofiles]

### ISSUE THREAD

**Issue by c5sire** [plantbreeding/API#183]
2 issues:

- should all result objects contain the data object?
- json names in the result object are missing apostrophes

**Comment by BrapiCoordinatorSelby** [comment]
Versailles Hackathon:

Discussed difference between 3 types of records
Discussed possibility of adding a data array to everything
Realized that that would be a breaking change for many. 
* Could mean that you repeat the master data in each element of the data array, but that would also mean increasing payload size.

**Comment by BrapiCoordinatorSelby** [comment]
With the development of BrAPI V2, this issue has been resolved. `markerProfiles` has been replaced with the GA4GH Variants Schema. The equivalent GA4GH entity is a `callSet`
To retrieve the same data:

(1) Filter by Germplasm
```
GET /callsets?germplasmDbId=DbId
-> Returns set of `callSet` entities 
   (will always have paginated `data` array)
```

(2) Retrieve genotype data
```
GET /callsets/{callSetDbId}/calls
-> returns genotype data for a single `callSet` 
   (will always have paginated `data` array)
```
OR
```
POST /search/calls 
    { "callSetDbIds": ["dbid1","dbid2","dbid3"...]}
-> returns SearchResultDbId 
   (will not have `data` array)

GET /search/calls/{searchResultDbId}
-> returns genotype data for all callSets in search list 
   (will always have paginated `data` array)
```
