### ISSUE TITLE
Document BrAPI multi crop implementation requirements

### ISSUE THREAD

**Issue by gcornut** [plantbreeding/API#185]
It would be nice to have a clear documentation of how to implement multi crop BrAPI endpoints. 
Some of the questions to answer in the documentation:

- Should every brapi endpoint (multi crop or not) implement the `/brapi/v1/crops` call? (probably not since we have the calls call)
- Are multi crop database forced to implement the `{crop}/brapi/v1` endpoints? (apparently not)
- Should the "calls" call be at `/brapi/v1/calls` or `{crop}/brapi/v1/calls` or both?

And of course the "crops" call should only appear at the root of the endpoint at `/brapi/v1/crops`

**Comment by gcornut** [comment]
Interesting related question:
https://github.com/plantbreeding/API/issues/130#issuecomment-363115923
From @homonecloco:
> What about Brassica rapa (https://en.wikipedia.org/wiki/Brassica_rapa)?. Which is a single species that provides several crops...

**Comment by BrapiCoordinatorSelby** [comment]
{crop}/brapi/v1 becomes {optionalDBServerName}/brapi/v1
/crops call becomes /commonCropNames
Add search by crop param
