### ISSUE TITLE
Give main objects (Germplasm, Study, ....) a link to descriptive web page

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#187]
Use case : data exchange (graingene <->T3), data search (INRA, WUR, VID, iBet, ....)
When fetching a json, for instance for germplasm, we need both 
- access to related JSON (JSON-LD functionality)
- access to source database web page (card for the current germplasm)

**Comment by BrapiCoordinatorSelby** [comment]
I added a documentation URL field to high level objects, leaving the JSON-LD functionality for v2
