### ISSUE TITLE
Discussion about BrAPI call aggregation/proxy between servers

### ISSUE THREAD

**Issue by guignonv** [plantbreeding/API#189]
**SUMMARY**
Sometimes, while you hold some data about your crops, you could grab some more data from other servers (either yours or others).

**USE CASES:**
For instance, in my case, I hold all the information about germplasm in my main database and have no data about markers or breeding. Guilhem, on his Gigwa server implementation of BrAPI, holds information about markers on some of our germplasm. Musabase holds some informations about germplasm breeding but does not really need to hold information about genebank germplasm (at least, it doesn't have the role to maintain such information).

Since I want to share all this information from one endpoint which is our BrAPI implemention on MGIS, I implemented 2 things corresponding to 2 different use cases:

1. call "proxy-ing": I don't handle marker calls on MGIS but rather transfer the user query to Gigwa server and then serve the Gigwa answer to my clients.

2. call "aggregation": MusaBase can implement the germplasmdetails call, provide local data and aggregate data from the same call done on MGIS.

**EXAMPLES:**
Example of use case 1:
https://www.crop-diversity.org/mgis/brapi/v1/maps
Calls in fact:
https://www.crop-diversity.org/gigwaDEV/rest/Musa_acuminata-v1/brapi/v1/maps

Example of use case 2:
From MusaBase:
https://musabase.org/brapi/v1/germplasm/65868
```
{
    "subtaxa": "",
    "germplasmSeedSource": "",
    "germplasmName": "ITC0609",
    "acquisitionDate": "",
    "subtaxaAuthority": "",
    "biologicalStatusOfAccessionCode": "",
    "instituteName": "",
    "defaultDisplayName": "ITC0609",
    "synonyms": [
      "Pahang"
    ],
    "countryOfOriginCode": "",
    "pedigree": "NA/NA",
    "commonCropName": null,
    "speciesAuthority": "",
    "genus": "genus",
    "species": "Musa",
    "donors": [],
    "typeOfGermplasmStorageCode": "",
    "accessionNumber": "ITC0609",
    "germplasmDbId": "65868",
    "instituteCode": "",
    "germplasmPUI": ""
  }
```

And the same call from MGIS:
https://www.crop-diversity.org/mgis/brapi/v1/germplasm/01BEL084609/
```
{
                "germplasmDbId": "01BEL084609",
                "defaultDisplayName": "Pahang",
                "germplasmName": "Pahang",
                "accessionNumber": "ITC0609",
                "germplasmPUI": "10.18730/9K93B",
                "synonyms": null,
                "commonCropName": "banana",
                "instituteCode": "BEL084",
                "instituteName": "ITC",
                "biologicalStatusOfAccessionCode": "100 wild",
                "countryOfOriginCode": "UNK",
                "genus": "Musa",
                "species": "subsp. malaccensis",
                "speciesAuthority": null,
                "subtaxa": null,
                "subtaxaAuthority": null,
                "donors": [
                    "IRFA",
                    "IRFA / MPL",
                    "CNPMF (01/11/85)",
                    "Ban. Board (01/06/79)",
                    "88 1/2 Milestone Bentong Kulalipis road, Palang Province (16/12/1947)"
                ],
                "acquisitionDate": "1989-05-25"
            }
```

As one can see, many fields are empty in the MusaBase database and it could populate those fields from MGIS using BrAPI.

**ISSUES TO DISCUSS**
The infinite loop issue:
There are basically 2 ways to aggregate data from other servers: static and dynamic. The "Static" way can be done by an admin running a script outside BrAPI which grabs the data and stores it (duplicate) locally in a file or a database or whatever. The data is static is the external BrAPI server providing that data can be offline, the local BrAPI server can still serve the data from its local static copy.
The second "dynamic" way is to grab the data "on-the-fly": the client access to the main (local) BrAPI server that will query the external BrAPI server to aggregate what that external server has to the local data. Then, the combined information will be served to the client.
In this later "dynamic" case, we should make sure the external server does not aggregate the data from our main server otherwise we would have an infinite loop, one server querying the other without being able to answer to the query it just received because it didn't get the answer from the other (itself waiting for the answer of the other server)!

Proposed solution: add in the URL a "callers" parameter with the list of BrAPI services who issued the call and add the trace of the sources in the metadata of the call answer, for instance:

```
...
metadata: {
  ...
  'aggregated_from': ["https://www.crop-diversity.org/gigwaDEV/rest/Musa_acuminata-v1/brapi/v1", ...]
}
...
```

When a server that does aggregation receives a query, it first checks if its BrAPI service URL is not in the list of "callers" and if so, it would not do aggregation (as it has already been done). If it's not, then it can aggregate and when calling other servers, it will add its URL in the "callers" URL parameter (while keeping previous URLs already specified in that parameter).
For instance, when MGIS BrAPI calls Gigwa, it adds to its query string "...&callers=www.crop-diversity.org%2Fmgis%2Fbrapi%2Fv1" (note: the protocol should not be included because it could be either http or https).

The aggregation issue
Aggregation on a simple object is easy but when you try to aggregate lists, then it is more complicated because you have to manage the pager and possibly duplicated elements...
Therefore, I don't think implementing aggregation on search calls or list calls is a good idea.

**Comment by BrapiCoordinatorSelby** [comment]
> The infinite loop issue:

Right now, this seems like a very specific problem and I would not feel comfortable trying to make a generalized solution part of the official BrAPI spec. I am certain that other groups will face the issue of aggregation from multiple source, but the infinite loop issue only becomes relevant if the sources are independently managed AND each source decides to aggregate data dynamically AND they do it without communicating with the developers of the other sources. In some distant future, I hope the community is big enough and that we have enough public BrAPI resources available that this situation could happen all the time. But for now, I think it is enough for you @guignonv and @GuilhemSempere to develop a workable system between yourselves, without the need to force generalization on everyone. 

Thinking a little outside the box, if there are system accounts setup for this sort of server to server authorization, you could probably avoid 1 layer of looping simply by knowing that a particular system account means that the request is coming from a particular source and not to send a query back to that source.

>The aggregation issue

As part of #192 (JSON-LD), each high level entity will be given a "PUI" field. If you have items in a list coming from 2 different sources, their PUI may be good enough to identify duplicate items. Pagination would still be a little tricky, or slow depending on how much pre loading of data the aggregator did and how the records were sorted. In general, an API should hide the specific implementation, so we can make recommendations as a community, but if people can build implementations which aggregate a list of data from multiple sources if they want.

I will close this issue for now. If you feel strongly that this solution needs to be generalized for the wider community, re-open the issue, or send me an email so we can talk it through.
