### ISSUE TITLE
Consistent naming of identifiers

### ISSUE THREAD

**Issue by c5sire** [plantbreeding/API#19]
Maybe this has been discussed now in Montpellier:

Internal database identifiers in V1 often end in xxDbId like germplasmDbId - one implication from examples is that it is an integer. The naming is not always uniform across identifiers as in markerId. Also, the same schema could be adhered to in the url calls and other documentation of a call.

**Comment by sebastian-raubach** [comment]
This most definitely shouldn't be an integer.

**Comment by lukasmueller** [comment]
It is already defined as a string in the documentation.

**Comment by jeback1** [comment]
I agree that we should be consistent and we did do a fair amount of clean up but clearly missed a few such as markerId.  I propose that we leave the clean-up of any remaining inconsistencies in the naming conventions to version 2.
