### ISSUE TITLE
Discrepancy in Vendor Plate

### ISSUE THREAD

**Issue by homonecloco** [plantbreeding/API#196]
The ```vendorBarcode``` field is defined only as ```barcode``` in the table documenting the return model. Also, ```vendorBarcodeImageURL``` is not described. 

https://github.com/plantbreeding/API/blob/master/Specification/ExternalVendorSamples/Vendor_PlateSearch_GET.md
compare model to: 
https://github.com/plantbreeding/brapi-Java-TestServer/blob/master/src/main/java/org/brapi/test/BrAPITestServer/model/rest/VendorPlate.java

**Comment by BrapiCoordinatorSelby** [comment]
fixed in the move to swagger documentation
