### ISSUE TITLE
Convert the API to a formal definition (swagger)

### ISSUE THREAD

**Issue by homonecloco** [plantbreeding/API#197]
To formalise the specification (even more), an unambiguous definition is required.

For that, there is a new branch:
https://github.com/plantbreeding/API/tree/swagger
and 
https://github.com/homonecloco/API/tree/swagger 

There are .json files for each .md file, and the 'final' version is a concatenated yaml for each group.

**Comment by gcornut** [comment]
Could we consider moving the JSON schema definitions from the [BrAPI validator repository](https://github.com/plantbreeding/IPK-BrAPI-Validator/tree/master/src/main/resources/schemas/v1.1) to this repository and then just refer to these into the swagger yaml files? @martinbaste 

Apparently the`$ref` field ([see Swagger OpenAPI specification](https://swagger.io/docs/specification/using-ref/)) can do this.

**Comment by homonecloco** [comment]
Are this definitions in swagger? As one of the features that swagger allows is tho have a description field. That can be used to have in the same place the documentation in MarkDown. I agree on the fact that having a single source for the validations and the documentations is a good practice.

**Comment by martinbaste** [comment]
@gcornut I use the JsonSchema as defined here: http://json-schema.org/ 

I believe it is the same as Swagger uses (in Json, instead of Yaml). It has the benefit that you have to actually define what is valid, which is a bit more concrete that the current implementation, and it can be used by software to define and validate.

We can move them here or to a dedicated repository other projects can depend on.

**Comment by BrapiCoordinatorSelby** [comment]
This is done!

The versions of JSONSchema used by Swagger and BRAVA are slightly different. For v1.2 Patrick still had to write the BRAVA spec by hand but we were able to confirm its accuracy with a Swagger generated BrAPI implementation. By v1.3, my hope is there will be a simple script conversion between the Swagger BrAPI spec and the BRAVA JsonSchema.
