### ISSUE TITLE
Should we always use the trailing '/' before the question mark for the parameters?

### ISSUE THREAD

**Issue by c5sire** [plantbreeding/API#20]
See for discussion and pointers to reference documents:

http://stackoverflow.com/questions/1617058/ok-to-skip-slash-before-query-string

**Comment by jeback1** [comment]
It does seem that the best practice is to include the slash.  I will propose that we consider this as an enhancement for v2.

**Comment by martinbaste** [comment]
Apparently the accepted answer quotes a spec that is currently obsolete. 

Here is a more [recent answer](https://stackoverflow.com/a/42193734/5436531) that says that according to the latest spec, it is acceptable to skip the slash.

**Comment by BrapiCoordinatorSelby** [comment]
This seems to be a great debate in the Web community, with no clear best practice. As @martinbaste has pointed out, both options are acceptable according to the official specs. So the argument mostly comes down to aesthetic's and personal preference.
It is a recommended best practice that a server should accept both versions of a given URI and treat them as the same.
The BrAPI documentation is pretty consistent on URI examples being without a trailing slash. I will make sure the all the calls and examples are consistent without trailing slashes, then I will close this issue.

If you feel there is a strong technical reason why it needs to be strictly defined one way or another, please reach out to me or open a new issue.
