### ISSUE TITLE
supporting multiple parameter values in some more calls

### ISSUE THREAD

**Issue by GuilhemSempere** [plantbreeding/API#200]
Some calls would benefit from having their parameters support CSV lists. This wouldn't break the current implementations since single values would remain supported by default. But this enhancement will greatly improve efficiency (we must keep in mind that genotyping data always gets bigger and nobody wants to invoke a call thousands / millions of time in a row: that would just kill the performance).

In my opinion:

- in /maps/mapDbId/positions the linkageGroupName parameter should support lists
- in /markerprofiles the germplasmDbId parameter should support lists

**Comment by BrapiCoordinatorSelby** [comment]
I'm trying really hard to move away from list parameters in GET calls. 
  A) There is not standard way to do it. Some libraries support CSVs, some libraries support repeat parameters, some libraries support JSON arrays. If I remember correctly, BrAPI v1.0 had different examples representing all 3 of these options
  B) The maximum URL size supported by most tools and browsers is about 2000 characters. Best case, assuming CSV list (most compressed option) and 6 char IDs, you are going to have a hard limit of about 285 IDs in your list. Worst case, you have about 40 items in your list. Sometimes this is enough, but generally for genotyping objects this limit is too small for comfort.

It is better to POST a query object with an arbitrarily large list of IDs, then GET the results of that search query.
