### ISSUE TITLE
Deprecation (Genome Map Details)

### ISSUE THREAD

**Issue by gordonstephen** [plantbreeding/API#203]
Apologies if this is covered elsewhere, but I was wondering what the intention of the documentation for the deprecation of the linkageGroups list in Genome Map Details is. Should we fill in the linkageGroups list as normal for now? Should we not fill it in at all? Should we fill it in with the text specified in the documentation? I'm just not quite sure how to interpret what's there.

Thanks,
Gordon

**Comment by BrapiCoordinatorSelby** [comment]
Sorry I didn't see this 6 months ago. I hope you've gotten the answer you were looking for before now. Just in case anyone is searching for a similar answer:
When a field in a response object is marked as "deprecated", then it should be considered deleted in that version. However, the field still needs to be available in the documentation to support backward compatibility.
In this example, in the v1.1 call "/maps/{mapDbId}" the field "linkageGroups" in the response object was removed and replaced by the field "data". 
- If you are building a server which supports v1.1 ONLY, then you should only include "data" in your response and ignore "linkageGroups". A client expecting a v1.1 response will be happy, A client expecting a v1.0 response will fail as expected. 
- If you are building a server which supports v1.1 and v1.0, then you should use include both "data" and  "linkageGroups" in your response. A client expecting a v1.1 response will be happy, with an extra field to ignore, A client expecting a v1.0 response will be happy, with an extra field to ignore, 

The supported versions of each call should be documented in the "/calls" call.
