### ISSUE TITLE
Seasons and studytypes in Study Object need to be made consistent

### ISSUE THREAD

**Issue by BrapiCoordinatorSelby** [plantbreeding/API#208]
#31 
Seasons have DbIds, which are not being used in the Study object. Outstanding question whether these DbIds are even needed? Seasons are pretty consistent and well understood ("season year"). the only advantage is being able to search by season or year alone.

Studytype have no DbId, but are not standardized and should be referenced by a key, not just by name. Propose adding studyTypeDbId to the studyType object and study object.

**Comment by gcornut** [comment]
I've also seen a weird inconsistency between  `/brapi/v1/studies-search` where the study name is `"name"` and  `/brapi/v1/studies/{id}` where it is  `"studyName"`

**Comment by BrapiCoordinatorSelby** [comment]
the seasons and names problems presented here have been handled in other issues. 
I'm going to leave StudyType as it is for right now. If anyone has a problem with how study types are handled, let me know and/or open a new issue please.
