### ISSUE TITLE
HTTP status code when errors occur

### ISSUE THREAD

**Issue by philipglaser** [plantbreeding/API#210]
From casual and impressionistic observation of several BRAPI implementations, it seems that even when errors are reported in the status collection of the meta data object, the http status code  remains 200. It has been suggested that the status code should be in the 500-and-above series in these situations. 

It has also been pointed out, on the other hand, that as long as the server's response is intelligible as BRAPI response, even if that response contains error messages, the status from the http point of view should remain 200. 

One way or another, the API spec should define the standard practice.

**Comment by hornySage** [comment]
I agree that the specification should define a standard practice.

Roy Fielding originator of REST developed it based on HTTP specification.

HTTP RFC states that:
Response status codes beginning with the digit "5" indicate cases in which the server is aware that it has erred or is incapable of performing the request.  Except when responding to a HEAD request, the server SHOULD send a representation containing an explanation of the error situation, and whether it is a temporary or permanent.

So I think it makes more sense to use a status code from 5XX.

**Comment by c5sire** [comment]
Makes sense to me, too.

**Comment by BrapiCoordinatorSelby** [comment]
I agree that we should be using standard HTTP response codes whenever possible. I'd like to piggy back this issue and ask the question, what is the purpose of the "status" array in the brapi metadata?

The use of "code" within each status object seems redundant. If your HTTP status is 500, do you need the status array to also contain a "500" code? In reality, I believe the the "status" objects are primarily used to send log data to be presented to the user (or developer). 

I propose that the structure of the "status" objects should be changed to the following:
{
    message: "this is a log message",
    messageType: "INFO"
}
where "messageType" can be any of the standard logging levels (INFO, DEBUG, WARNING, ERROR, etc)

**Comment by sazeMode** [comment]
One valid use case for status array is if there is a request for data extraction then an asyncId is provided in the status which is queried till completion.

It seems that the use of "code" is redundant. For the above case if HTTP response is 200 then  we can assume that status is JobId.

{
message: "this is a log message",
messageType: "INFO"
}
There is no issue with this status structure . But it looks like an overkill. We can just have a message field which when combined with HTTP status code can give complete information. I think we dont care MessageType unless it is error,  when we go bat crazy :)

**Comment by BrapiCoordinatorSelby** [comment]
I think #146 covers your asyncID concerns.

messageType may be overkill, but I'd like to give people the flexibility to produce meaningful log messages. HTTP status codes can only distinguish between error and success. 
For example, a PUT request might return code 200, but you may want to include a INFO or WARNING message to the user that says "the ID was not found, therefore a new object was created".

**Comment by sazeMode** [comment]
Then this seems ok.

**Comment by barrow-wight** [comment]
Getting in late but perhaps a consideration is whether we are only using
HTTP as the transport protocol or not.

Consider sending an instruction to someone via snail mail envelope. If the
instruction has an error you shouldn't get an error reported by the
delivery system.

Or the layers in ISO network protocols. Each wrapped protocol is opaque to
the wrapping protocol.

**Comment by BrapiCoordinatorSelby** [comment]
If anyone intends to use a different transfer protocol, I'd be happy to work with them to adapt the BrAPI specifications, BUT BrAPI is built on the assumption that you are using HTTP. I don't think it is productive to question that assumption unless there is a real need to do so.

Using HTTP error codes is an accepted best practice in the RESTful web service community. To continue your snail mail analogy, imagine if the post office provided a form letter with a checkbox for the reason you didn't accept the letter. Every sender (client) already knows what that form letter means and how to handle it, coming from any receiver (server). I'm stretching the metaphor a bit now, but the point is the HTTP status codes provide an established ontology for handling most errors.

**Comment by barrow-wight** [comment]
I wasn't suggesting that we should change the transport protocol !

As a consumer of APIs what i like to have is the situation where when I get
an error response i can figure out what had gone wrong.

This is not always the case when HTTP error codes are used for errors in
the wrapped request.

When that happens a developer can waste valuable time.
