### ISSUE TITLE
Add marker and sample counts to allelematrices

### ISSUE THREAD

**Issue by philipglaser** [plantbreeding/API#214]
A data list item in the allelematrices response is currently defined as follows: 

`{  
         "name":"testDs1",
         "matrixDbId":"27",
         "description":"a test dataset",
         "lastUpdated":"2017-06-12",
         "studyDbId":"abc123"
      }`

GOBII and JHI propose adding two new keys: markerCount and sampleCount. 

The use case occasioning this proposal is the extraction of datasets from GOBII in FlapJack. In FlapJack, it would be useful to assess the size of the matrix, based on the marker and sample counts, so as to warn the user if a particular extract is at risk of taking a long time.

**Comment by GuilhemSempere** [comment]
+1

**Comment by BrapiCoordinatorSelby** [comment]
Fixed in V2.0
07017629ea717cb2fc80958a65774ccaffe1335d

AlleleMatrices becomes VariantSets in V2.0
