### ISSUE TITLE
"Call" call response does not include "features"

### ISSUE THREAD

**Issue by BrapiCoordinatorSelby** [plantbreeding/API#217]
_From @guignonv on August 25, 2016 16:17_

As stated in the Germplasm calls ( http://docs.brapi.apiary.io/#reference/germplasm/call-search ), the client can tell if the server can provide MCPD data using the "brapi/v1/call" call. But in the documentation of the "call" call, the feature hash has disappeared.

The response data types should include:
"features   object  Hash of features supported by this call     N"

The response body should be:
`{
  "metadata": {
    "pagination": {
      "pageSize": 3,
      "currentPage": 0,
      "totalCount": 3,
      "totalPages": 1
    },
    "status": null,
    "datafiles": []
  },
  "result": {
    "data": [
      {
        "call": "allelematrix",
        "datatypes": [
          "json",
          "tsv"
        ],
        "methods": [
          "GET",
          "POST"
        ]
      },
      {
        "call": "germplasm/id",
        "datatypes": [
          "json"
        ],
        "methods": [
          "GET"
        ],
        "features": [
          "MCPD": "yes",
          "MCPD-version": "V.2.1"
        ]
      },
      {
        "call": "doesntexistyet",
        "datatypes": [
          "png",
          "jpg"
        ],
        "methods": [
          "GET"
        ]
      }
    ]
  }
}`

_Copied from original issue: plantbreeding/Documentation#30_

**Comment by BrapiCoordinatorSelby** [comment]
_From @sebastian-raubach on August 25, 2016 17:39_

The content of `features` doesn't appear to be valid json. Is it an array of objects or an array of strings or something else? Writing from my phone just now, so can't really change it. 
Also, if it's an array of objects, then the keys probably shouldn't be values, i.e `MCPD` shouldn't be a key.

Maybe something like this:

``````
{  
    "metadata":{  
        "pagination":{  
            "pageSize":3,
            "currentPage":0,
            "totalCount":3,
            "totalPages":1
        },
        "status":null,
        "datafiles":[  

        ]
    },
    "result":{  
        "data":[  
            {  
                "call":"allelematrix",
                "datatypes":[  
                    "json",
                    "tsv"
                ],
                "methods":[  
                    "GET",
                    "POST"
                ]
            },
            {  
                "call":"germplasm/id",
                "datatypes":[  
                    "json"
                ],
                "methods":[  
                    "GET"
                ],
                "features":[  
                    {  
                        "name":"MCPD",
                        "version":"V.2.1"
                    }
                ]
            },
            {  
                "call":"doesntexistyet",
                "datatypes":[  
                    "png",
                    "jpg"
                ],
                "methods":[  
                    "GET"
                ]
            }
        ]
    }
}```
``````

**Comment by BrapiCoordinatorSelby** [comment]
_From @lukasmueller on September 9, 2016 20:34_

Valentin, do you agree with this suggestion?

**Comment by BrapiCoordinatorSelby** [comment]
_From @jackeblagare on September 12, 2016 2:20_

@sebastian-raubach, that looks like a reasonable response.

**Comment by BrapiCoordinatorSelby** [comment]
@guignonv this issue is very old. is it still relevant?
#213 will provide an explicit call for mcpd data, which should solve your issue. 
Are there any other features?

**Comment by guignonv** [comment]
I don't see any.
