### ISSUE TITLE
Use of data element in result

### ISSUE THREAD

**Issue by c5sire** [plantbreeding/API#22]
The 'data' element is not always used to contain the main results - compare 'programs', crops, genome maps, and 'germplasm related calls'.

**Comment by lukasmueller** [comment]
Yes, this is a feature. Data only contains *paginated* results.

**Comment by jeback1** [comment]
Reinhard, I agree that this is a feature and will close this issue.  Please re-open if you disagree.

Thanks,
Jan Erik
