### ISSUE TITLE
Add phenotype search by observationUnit?

### ISSUE THREAD

**Issue by dauglyon** [plantbreeding/API#230]
The current spec for phenotype search does not allow one to search by specific observationUnits (e.g. give a list of observationUnitIds and receive back those plots and their phenotypes).

**Comment by patrick-koenig** [comment]
What would be a use case?

**Comment by dauglyon** [comment]
@patrick-koenig Assuming one has a list of plots which have previously been phenotyped, being able to check the status of those plots currently. (e.g. I have three plots on some study which i am particularly interested in, it doesn't make much sense to download the phenotypes for all plots in the trial and then need to post-process that, especially considering the data is returned as a list of obsUnits)

**Comment by dauglyon** [comment]
It also just seems strange to have a search function where one cant search by what is presumably the primary key of the results list
