### ISSUE TITLE
Add fields to location

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#231]
We are using the following fields for our location data, they might be of interrest for other groups:
'Site status' 
'Coordinates precision' (the site, the nearest town, a 10 kilometers radius circle, ...)
'Slope' (or aspect ?)
'Exposure'
'Environment type' (forest, field, nursery, ...)
'Topography' 
'Comment'

**Comment by BrapiCoordinatorSelby** [comment]
what are acceptable or example values for 'Site status', 'Exposure', and 'Topography'?

**Comment by cpommier** [comment]
For 'Site status' : Specific, INRA, Private, Public
'Exposure': 
flat, SO,310, full sun, 241, N-E
