### ISSUE TITLE
Add plotNumber field to 'Plot Layout Details' of a study.

### ISSUE THREAD

**Issue by aco46** [plantbreeding/API#235]
Plot number field is missing from Plot Layout Details of a study.

**Comment by BrapiCoordinatorSelby** [comment]
Plot Layout Details by study doesn't exist in V2.0 any more after an attempt to decouple the concepts of Study and Observation Unit a little bit and move them into separate modules. To retrieve the same information in V2.0 use 
`GET /observationunits?studyDbId={studyDbId}` 
this will retrieve all the positional information for each observation unit, including `plotNumber`
