### ISSUE TITLE
datafiles in metadata key may need a filetype information

### ISSUE THREAD

**Issue by puthick** [plantbreeding/API#242]
Currently, datafiles is an array of file URLs like:

"datafiles" : ["/mnt/local/matrix_01.csv",  "/mnt/local/matrix_02.csv"]

These example files have .csv that suggest they are csv files.

I want to alert the fact that currently the file type is derived from the file extension.

**Comment by BrapiCoordinatorSelby** [comment]
fix for V2.0 in e1bdc794d1b11b65333ada76900bc4ea2a8275ea
