### ISSUE TITLE
phenotype-search inconsistent search params

### ISSUE THREAD

**Issue by nickmorales** [plantbreeding/API#248]
e.g. observationVariableDbId in GET call and observationVariableDbIds in Table call

**Comment by BrapiCoordinatorSelby** [comment]
The example provided was done that way on purpose to show the difference between a single DbId in the GET vs and array of DbIds in the search. 

Also, phenotype-search no longer exists, so I'm closing this issue. If you find any more inconsistent parameter please create a new issue.
