### ISSUE TITLE
Inconsistent baseurls of data providers

### ISSUE THREAD

**Issue by c5sire** [plantbreeding/API#25]
Several base urls given in the brapi-resources.json file are not compliant with the definition of the url structure in the BrAPI overview. That is:

http[s]?://my.crop.org/[crop]?/brapi/v1/

**Comment by lukasmueller** [comment]
I guess it is ok to have additional levels after the domain name, before the brapi/ ?

**Comment by jeback1** [comment]
Having an optional crop in the url is specified in the introduction as a way for systems that support multiple crops to specify the crop:

"To distinguish between multiple databases or crops available from the same server, include the database or crop name as part of the "\<server\>" identifier.

Example: superBreedingServer.org/maize/brapi/v1/markerprofiles/2939"

**Comment by lukasmueller** [comment]
fixed in 112fcc6e2ff5d23955488904995c4a59e1ef58f7.
