### ISSUE TITLE
Single Marker BrAPI call

### ISSUE THREAD

**Issue by dauglyon** [plantbreeding/API#252]
We need a call to allow one to query the intersection between accession and marker. So, rather than getting a whole markerprofile, ask "What is the genotype of accession X at marker position Y"

**Comment by lukasmueller** [comment]
Or also filter by marker state... give me the lines that have this state etc. Maybe should be another ticket.

**Comment by BrapiCoordinatorSelby** [comment]
New GA4GH schema allows for this
