### ISSUE TITLE
Add call for creating new observations of existing ObservationUnits without need for studyDbId

### ISSUE THREAD

**Issue by bellerbrock** [plantbreeding/API#255]
Use Case: A user exports a set of observations from the fieldbook app and loads them into HIDAP to do a data quality check and some basic analysis. Then the user stores them in sweetpotatobase.org using BrAPI calls

Call 1: Retrieve access_token using the existing [token](https://brapi.docs.apiary.io/#reference/authentication/authentication/login) call. To be upgraded to full OAuth2.0 login in the future
Call 2:  Create observations using new version of [studies/studyDbId/observations](https://brapi.docs.apiary.io/#reference/study/observations-for-a-study/create-or-update-observations-for-a-study) call that does not require studyDbId, just the access token and for each observation:
"observationUnitDbId", "observationVariableDbId", and "value". 
Optional fields "collector" and "observationTimeStamp" would be used if available (when user exports in database format from the fieldbook app)

Example data in fieldbook export file:

| plot_name  | plot_id | NOPE &#124; CO_331:0000192 |
| ------------- | ------------- | ------------- |
| 2018ASPGH_STO41-FUMESUA_1  | 153020  | 30 |
| 2018ASPGH_STO41-FUMESUA_2  | 153046  | 240 |

240 flagged and corrected to 24 during HIDAP quality check

Example body:
```
{
  "access_token":"vudukgeracropsfvjbnbhotuucndkkpmhmlosjnkerslhbnbvemswdhcfkkojtocphqmbro",
  "observations": [
    {
      "observationUnitDbId": "153020",
      "observationVariableDbId": "CO_331:0000192",
      "value": "30"
    },
    {
      "observationUnitDbId": "153046",
      "observationVariableDbId": "CO_331:0000192",
      "value": "24"
    },
  ]
}
```

**Comment by bellerbrock** [comment]
Ok, after some additional discussion we're thinking we may need an observations-search call before submitting the new observations to check if the combination of observationUnitDbId and observationVariableDbId already exists in the db. 

That way if it does the user can determine if they want still want to create the new observation (POST), update the existing one (PUT) or skip it entirely. 

Based on the germplasm search it could look something like:
/brapi/v1/observations-search

body:
```
{
    "observationUnitDbIds": [ "153020","153046"]
}
```
response:
```
{
"observations": [
  {
    "observationUnitDbId": "153020",
    "observationVariableDbId": "CO_331:0000192",
    "value": "29"
  }
 ]
}
```

**Comment by BrapiCoordinatorSelby** [comment]
below is a draft of the BrAPI standardized versions of the calls you have requested here

Notes: 
* Access Tokens should be a header parameter of every request, not in the body.
* In BrAPI, PUT is used to create and update specific objects. The presence or absence of a DbId determines if it will create or update

PUT /brapi/v1/observations
body
{
  "observations": [
    {
      "collector": "string", //optional
      "observationDbId": "string", // if populated then update existing otherwise add new
      "observationTimeStamp": "2018-06-19T18:59:45.751Z", //optional
      "observationUnitDbId": "string", //required
      "observationVariableDbId": "string", //required
      "value": "string" //required
    }
  ]
}
response
{
  "metadata": {
    "datafiles": [],
    "pagination": {
      "currentPage": 0,
      "pageSize": 1000,
      "totalCount": 2,
      "totalPages": 1
    },
    "status": []
  },
  "result": {
    "data": [
      {
        "germplasmDbId": "8383",
        "germplasmName": "Pahang",
        "observationDbId": "12345",
        "observationLevel": "plot",
        "observationTimestamp": "2015-11-05T15:12:56+01:00",
        "observationUnitDbId": "11",
        "observationUnitName": "ZIPA_68_Ibadan_2014",
        "observationVariableDbId": "CO_334:0100632",
        "observationVariableName": "Yield",
        "operator": "Jane Doe",
        "studyDbId": "35",
        "uploadedBy": "dbUserId",
        "value": "5"
      }
    ]
  }
}

POST /brapi/v1/observations-search
body
{
    "collector": ["string","string"], //optional
    "observationDbId": ["string","string"], //optional
    "observationUnitDbId": ["string","string"], //optional
    "observationVariableDbId": ["string","string"] //optional
}
response
{
  "metadata": {
    "datafiles": [],
    "pagination": {
      "currentPage": 0,
      "pageSize": 1000,
      "totalCount": 2,
      "totalPages": 1
    },
    "status": []
  },
  "result": {
    "data": [
      {
        "germplasmDbId": "8383",
        "germplasmName": "Pahang",
        "observationDbId": "12345",
        "observationLevel": "plot",
        "observationTimestamp": "2015-11-05T15:12:56+01:00",
        "observationUnitDbId": "11",
        "observationUnitName": "ZIPA_68_Ibadan_2014",
        "observationVariableDbId": "CO_334:0100632",
        "observationVariableName": "Yield",
        "operator": "Jane Doe",
        "studyDbId": "35",
        "uploadedBy": "dbUserId",
        "value": "5"
      }
    ]
  }
}

**Comment by bellerbrock** [comment]
Great! This is just what we needed. And thank you for the clarifications and examples

**Comment by bellerbrock** [comment]
Mostly implemented. Additional work includes:

- Implement [suggested error codes](https://brapi.docs.apiary.io/#introduction/structure-of-the-response-object:/the-metadata-key) in metadata key

- Modify FileRequest object to only create a temp file, then use fileUpload to handle archiving in standardized path format. 

- Harmonize StorePhenotypes and StoreObservations modules. Maybe a plugin system for different Storing options that avoids duplication as much as possible would make sense?

- Explore possibility of adding timestamp column to phenotype table. Would require Chado schema update, but will be important for own uploads and brapi uploads. Once timestamp is easily retrievable we can start to prevent addition of new observations if combination of unit,  variable, and timestamp (or lack thereof) is not distinct

**Comment by BrapiCoordinatorSelby** [comment]
BrAPI V2.0
`POST /observations` endpoint added (along with others) for manipulating Observations independently.
