### ISSUE TITLE
regression in programs and programs-search call

### ISSUE THREAD

**Issue by mverouden** [plantbreeding/API#262]
Since version 1.2 one of the parameters is commonCropName, this parameter is missing on swaggerhub for version 1.2. It is also missing on both Github and Swaggerhub for version 1.3.

Also the test-server is missing commonCropName as column in the /brapi/v1/programs call and in the body of the /brapi/v1/programs-search call.

So far I have not found a database (BTI or multicrop) that has implemented querying by the commonCropName parameter. This makes it impossible to test this functionality in the BrAPI R pacakge.

**Comment by BrapiCoordinatorSelby** [comment]
documentation fixed, test-server will be updated to v1.3 soon
