### ISSUE TITLE
Property Named class

### ISSUE THREAD

**Issue by peterrosario** [plantbreeding/API#264]
Because some resources (e.g., Method and Trait) have properties named "class," the Android client code generator overrides getClass().  In Java Object.getClass() is declared final so the code doesn't compile.  (A solution is to change the property name which solves my problem but creates problems for others.)

**Comment by BrapiCoordinatorSelby** [comment]
fixed in V2.0
e15b8edd4109b675c37b14ede1f03c04713aab8f
