### ISSUE TITLE
inconsistency studies-search (POST) specification

### ISSUE THREAD

**Issue by mverouden** [plantbreeding/API#267]
**INCONSISTENCY**
When checking the specification of the studies-search (POST) call I have noticed an inconsistency between GITHUB and Swaggerhub.
In the GITHUB specification the request body commonCropName can be specified, however this missing in the body of the example value model on SwaggerHub.

**QUESTION**
Apart from this inconsistency I was wondering why the parameters of the studies-search GET and POST methods are different? The "Search Services" description states 

> These rules for search parameters apply to both GET call query parameters and POST call body parameters.

Also a studies-search get call should allow to search studies with two different studyDbId values (/brapi/v1/studies-search?studyDbId=35,345). However in the studies-search post call the body parameter is called studyDbIds. In my opinion it would make sense to keep the names of the parameters the same, regardless whether they appear as arguments in the get call or in the body of a post call.

**Comment by BrapiCoordinatorSelby** [comment]
I will fix the inconsistency in SwaggerHub. The commonCropName was lost during the translation from Apiary to Swagger format.

> why the parameters of the studies-search GET and POST methods are different?
The sentence you referenced from "Search Services" was talking about how searching should work and the rules for applying filters. It was not talking about the input parameters for the different services. I agree it usually makes sense for the GET and POST calls to match parameters but it is not strictly speaking necessary and hasn't been defined as a best practice for BrAPI ... yet. Feel free to open an issue if you'd like all the GET and POST parameters synced up.

> Also a studies-search get call should allow to search studies with two different studyDbId values 
We've gone back and forth on this a couple times. Right now ```studyDbId``` is defined as a single string, not an array. There is no single RESTful Best Practice for passing arrays in GET requests, which means there are several different standards and can be highly dependent on the language/library the server is using. 
My recommendation would be, if you want only 2 (small, fixed number) studies, call ```GET /studies-search``` twice. Or better yet call ```GET /studies/{studyDbId}``` twice. If you want an arbitrary or large number of studies, use ```POST /studies-search``` with an array of IDs.
In my opinion, the most RESTful version of this would be to replace ```GET /studies-search``` with ```GET /studies``` with the single item parameters and ```POST /studies-search``` to submit a search object with many values. But we can leave that kind of massive refactoring for BrAPI Version 2.
