### ISSUE TITLE
Consistency in markerprofiles return data

### ISSUE THREAD

**Issue by nickmorales** [plantbreeding/API#272]
the markerprofiles search call has 
{
        "markerprofileDbId": "993",
        "germplasmDbId": "2374",
        "uniqueDisplayName": "MyFancyGermplasm",
        "sampleDbId": "3937",
        "extractDbId": "3939",
        "analysisMethod": "GoldenGate",
        "resultCount": 1470
      }
while the markerprofiles details call has 
{
        "germplasmDbId": "993",
        "uniqueDisplayName": "MyNameHere",
        "extractDbId" : "38383", 
        "markerprofileDbId": "37484",
        "analysisMethod": "GBS-Pst1",
        "data" : [ { "marker1": "A" }, { "marker2":"A/B" }, ... ]
   }

i think the sampleDbId should be in both

**Comment by BrapiCoordinatorSelby** [comment]
BrAPI V2.0
`markerprofiles` is replaced with `callsets` and every `callset` has a sample DbId
