### ISSUE TITLE
studies-search GET/POST response

### ISSUE THREAD

**Issue by mverouden** [plantbreeding/API#273]
The studies-search POST call allows for searching by studyNames. Both the POST and GET call have in their response object name as ouput. I propose to rename those to studyName to make it more clear what name signifies.
I think this holds for many calls and not only the studies-search response.
e.g.
/programs: name -> programName
/programs-search: name -> programName

**Comment by BrapiCoordinatorSelby** [comment]
I believe this is covered by #171 which is fixed in pull #261

**Comment by mverouden** [comment]
True that it is covered by #171 and pull #261 should have fixed all generic name fields. However, there are still some calls that have generic name fields in their response objects.
E..g. studies-search (GET/POST), programs-search, programs

**Comment by BrapiCoordinatorSelby** [comment]
Oh you are right, I fixed the internal model files, but not the example responses. Good catch!

**Comment by mverouden** [comment]
Thanks Peter. Good I am still awake, just before my holidays start.

Please also check the test-server content, I guess that will also need to be updated.

**Comment by BrapiCoordinatorSelby** [comment]
the test-server is still on v1.2 and will not get any v1.3 changes until it is officially released.
