### ISSUE TITLE
lower case for all calls

### ISSUE THREAD

**Issue by c5sire** [plantbreeding/API#274]
commonCropNames should be 'commoncropnames' in 1.3

**Comment by dlebauer** [comment]
There is still camelcase for commoncropnames in the examples ... 

https://app.swaggerhub.com/apis/PlantBreedingAPI/BrAPI/1.3#/Crops/get_commoncropnames

![image](https://user-images.githubusercontent.com/464871/56964027-a0c4ee00-6b5a-11e9-9ee8-6ba733835f01.png)
