### ISSUE TITLE
Searches and filters as resource end points

### ISSUE THREAD

**Issue by c5sire** [plantbreeding/API#277]
There is some indication on some sources (for example https://stackoverflow.com/questions/5020704/how-to-design-restful-search-filtering) that searches could be there own resource. That is also in a sense true already. But it could be made plainer by replacing the '-' with '/' such that:

germplasm-search -> germplasm/search (or applying pluralization) -> germplasms/searches

**Comment by BrapiCoordinatorSelby** [comment]
Yes this is already part of the plan for V2. I'm very hesitant to put this large a change in V1 because dealing with the backward compatibility would be a nightmare.

**Comment by BrapiCoordinatorSelby** [comment]
Here we are 10 weeks and a hackathon later and I've changed my mind hahaha. 
search calls were re-designed in issue #168 
it is now '/search/germplasm' 
the primary reason for the 'search' first in the path is that there could be a conflict with '/germplasm/{DbId}' if your DbId happened to be the word 'search'
