### ISSUE TITLE
Should the API reflect the hierarchy of programs/trials/studies?

### ISSUE THREAD

**Issue by c5sire** [plantbreeding/API#280]
/programs
/programs/{programDbId]
/programs/{programDbId]/trials
/programs/{programDbId]/trials/{trialDbId}
/programs/{programDbId]/trials/{trialDbId}/studies
/programs/{programDbId]/trials/{trialDbId}/studies/{studyDbId}

**Comment by BrapiCoordinatorSelby** [comment]
The major down side to a structure like this is you have to know ALL of the ids in the hierarchy to make a call. If someone just gave you a studyDbId, you would be stuck. 
To solve this, you might include single ID calls as well ( `/studies/{studyDbId}`) but now you have a redundant call:
`/studies/{studyDbId}`
And
`/programs/{programDbId]/trials/{trialDbId}/studies/{studyDbId}`
both return the same thing. Of those 2 options guess which people are more likely to use 😄 

If we wanted to do something like this, I would advise stopping at 2 layers of hierarchy per call. so more like:
`/programs`
`/programs/{programDbId}`
`/programs/{programDbId}/trials`
`/trials/{trialDbId}`
`/trials/{trialDbId}/studies`
`/studies/{studyDbId}`
`/studies/{studyDbId}/observationunits`

This is pretty close to what we have now. The question is which of these is more preferable 
`/programs/{programDbId}/trials`
OR
`/trials?programDbId={programDbId}`

**Comment by cpommier** [comment]
This triggers a related question in Elixir/Emphasis. Indeed Program and Trials are just a way to regroup studies which is specific of the CGIAR breeding programs. In other communities we more often find datasets, project and from time to time project>dataset. An elegant solution might be to have a more generic dataset or study group object, typable, with additional fields (DOI, description, related papers, all MIAPPE.Investigation related field maybe, ...) 
@BrapiCoordinatorSelby Shall I create a separate issue for this so we can discuss this in preparation of the next hackathon.

**Comment by BrapiCoordinatorSelby** [comment]
Over the past year, I have been maintaining the position that I am not going to change the names or hierarchical order of Program, Trial, or Study. This is because every group and tool I've worked with, both inside and outside the CGs, has a different name and ordering for how they group their data. 

A generic grouping structure might work, but if it is too generic then it won't be helpful for anyone. If we add enough detail to make it helpful, I'm afraid we might end up with something very similar to what we have already.

That said, I am of course open to discussing it with you and the community. This issue captures our thoughts fairly well, but you are always welcome to open new issues if you feel it is necessary.

**Comment by cpommier** [comment]
Let's reopen that thread.
We simply need to be able to handle the notion of Project.
We could force that into Program.
Or we could simply add a project name at the Study (or Trial or Program) level.

**Comment by BrapiCoordinatorSelby** [comment]
I would think of Project as relatable to a BrAPI Trial. In fact, I just found an old piece of documentation which seems to have been accidentally lost. 
>The trial concept in BrAPI corresponds to the "investigation" concept in MIAPPE
[BrAPI 1.1](https://brapiarchive11.docs.apiary.io/#reference/trials)

So what about this for some definitions:

**Program** - Represents a long term effort by an organization. Usually associated with a single crop and represents a team of people. A Program may produce many projects and publications. 
_Synonyms: Breeding Program, Lab, Team_ 

**Trial** - Represents a specific effort which produces one or many sets of data. Can be run for a specific amount of time, and can be associated with multiple publications produced in that time.   
_Synonyms: Investigation, Project, Study Group_

**Study** - Represents a specific effort which produces one set of data for a specific season and location. May produce phenotypic data, genotypic data, or both.
_Synonyms: Experiment, DataSet_

DataSet maps to Study and Project maps to Trial. 
Does that work @cpommier? Is Trial missing any critical fields to represent a Project?

**Comment by cpommier** [comment]
Hi,

a project can produce several datasets, including for instance one phenotyping network (ie trial/investigation in my mind) some greenhouse studies (groupes under the same trial possibly) and genotyping data. All of those can be done with the same diversity panel.

I think there is really a distinction be tween datasets and projects, and therefore that a project can have multiple trial/investigation. Therefore a project is closer to the notion of program, while not being exactly the same. It could work if a Program has a type and that type can be project for instance.

Hope that helps

**Comment by BrapiCoordinatorSelby** [comment]
Cyril and I had a good chat in the during the BioHackathon (#BioHackathonEurope2019) and I think we have resolved this. 
PHIS has the concept of a Project, but it maps very clearly to BrAPI Trial.
GnpIS has the concept of a Project Name which is almost a tag outside the general hierarchy. There was a long discussion of adding a `projectName` field to BrAPI to facilitate the grouping of different BrAPI Trial/Studies as needed. With a quick poll around the room, it was determined that GnpIS is the only system which needs this functionality. So it is decided that the GnpIS group will manage their `projectName` as an additionalInfo. If there is anyone else in the community who sees this and would like to discuss this type of structure, please reach out to me so we can discuss your needs.
