### ISSUE TITLE
BrAPI calls returning non-JSON data

### ISSUE THREAD

**Issue by BrapiCoordinatorSelby** [plantbreeding/API#291]
There is no clear documentation on how to return non-JSON data formats with BrAPI.
should the response contain the file contents or should it be a URL in the dataFiles array?

**Comment by barrow-wight** [comment]
Given that the data may be voluminous, perhaps returning a URL (along with another value indicating the mime-type of the URL's target) would be an option (and maybe a hint to the file size?).

That provides the client with information that could be referred to the end-user for a decision regarding retrieval.

**Comment by BrapiCoordinatorSelby** [comment]
`/observations/table` requests can be sent with an `Accept` header which defines the format of the response (JSON, csv, or tsv)
`/images` takes care of image files
`/vendor/orders/results` takes care of genotype data files
`metadata.datafiles` has been expanded for #242 to allow better handling of any supplementary data files. 

It is not exactly standardized, but I believe it is at least documented on how to handle non-JSON data in these situations.
