### ISSUE TITLE
germplasmMarkerprofilesList should probably have a data array with Markerprofile objects inside

### ISSUE THREAD

**Issue by dauglyon** [plantbreeding/API#293]
https://github.com/plantbreeding/API/blob/master/Specification/ModelDefinitions/germplasmMarkerprofilesList.yaml

Currently returns a list of ids not in the data array.

**Comment by BrapiCoordinatorSelby** [comment]
BrAPI V2.0
`markerprofiles` has been replaced, issue is now irrelevant 
search `callSets` by GermplasDbId for equivalent list.
