### ISSUE TITLE
phenotypes-search GET call  documentation consistency and deprecation

### ISSUE THREAD

**Issue by mverouden** [plantbreeding/API#295]
In the header of the phenotypes-search GET call most optional parameters are given in plural form, whereas the parameter specification states they ought to be strings (singular DbId value).

After talking to @BrapiCoordinatorSelby I learned that the GET call is supposed to be using singular DbId values for the optional parameters. This makes perfect sense, because specifying e.g. many germplasmDbIds and studyDbIds could potentially result in a very long call url causing you would have to use a POST call.

The POST call covers the GET call functionality and, therefore, I propose to deprecated the GET call in v1.3 of the BrAPI specification.

**Comment by BrapiCoordinatorSelby** [comment]
handled in #168 
GET /phenotypes-search is now GET /observationunits
POST /phenotypes-search is now split into POST /search/observationunits and GET /search/observationunits
