### ISSUE TITLE
data parameters for study-search call

### ISSUE THREAD

**Issue by marieALaporte** [plantbreeding/API#31]
_From @nickmorales on October 19, 2016 13:48_

http://docs.brapi.apiary.io/#reference/study/search-studies/search-studies

POST Data parameters:
{
   "studyType" : "Trial",
   "studyNames" : ["Study A", "StydyB"], 
   "studyLocations" : ["Kenya", "Zimbabwe"], 
   "programNames": ["Test Program", "Program2"],
   "germplasmDbIds" : [ "CML123", "CWL123"],
   "observationVariableDbIds": ["CO-PH-123", "Var-123"]
   "active" : "true",
   "sortBy" : "studyDbId",
   "sortOrder" : "desc"
}

Maybe these parameters should only be DbIds like in other calls? Specifically, studyDbId, studyTypeDbId, locationDbId, and programDbId instead of studyNames, studyType, studyLocations, and programNames.

_Copied from original issue: plantbreeding/Documentation#37_

**Comment by marieALaporte** [comment]
_From @gcornut on October 21, 2016 14:4_

We have been using the "programNames", "studyLocations" and "studyNames" parameters because we consider these values as unique in our database and in our partner database [PHIS](http://web.supagro.inra.fr/phis/web/).

We are not against adding "studyDbIds", "locationDbIds" and "programDbIds" as parameters though.
Adding a "studySeasons" parameter would be also very useful. If i'm not mistaken the season is considered as a unique identifier.

In general "dbIds" are better but I feel like we impose identifier on some fields like study type or study season that don't need an identifier. For example, there should be only one "Winter 2006" season and only one "trial" study type, there is no need for a season identifier or a study type.

**Comment by lukasmueller** [comment]
Let's re-visit this in version 2.
