### ISSUE TITLE
observationUnitPhenotype.observationLevels should be an object, not a string

### ISSUE THREAD

**Issue by BrapiCoordinatorSelby** [plantbreeding/API#324]
from @dauglyon 

why this `"observationLevels": "block:1;plot:4;plant:4"` and not this
```
"observationLevels": {
  "block":"1",
  "plot":"4",
  "plant":"4"
}
```

It seems weird to force people to build a parser for that string when they’re probably already using a JSON parser

**Comment by cpommier** [comment]
It was historicaly easier in our software because it allowed to precise the hierarchy of levels.
Indeed, some experimental platforms will use rep>block>plot, others rep>plant, rep>block>plant or possibly rep only.
It is a simple way to adresse the lack of agreed level ontology. 
@gcornut what do you think of this? is it still required for us with the elixir plant data search / gpds development?

**Comment by gcornut** [comment]
Yes the object format has the advantage of being easy to parse and we could generate it easily.
The problem (as @cpommier said) is that with the object format we can't use the order of the levels to specify the hierachy of the level as JSON o bjects can't guarantee the order of there keys.

From https://www.json.org/ 
> An object is an unordered set of name/value pairs. [...]

If we wan to model an observation unit at the plant level which is part of a repetition level, itself part of a plot level we could do something like:
```json
"observationLevels": [
   { "type": "plot", "value": "1" },
   { "type": "repetition", "value": "2" },
   { "type": "plant", "value": "3" }
]
```
Assuming we explicitly define the order of levels to be from the largest to the smallest.
Alternatively we could also reference the parent level inside a level or we could define the level hierachies in an other BrAPI call (like /study/id/layout)

**Comment by BrapiCoordinatorSelby** [comment]
Proposal

```
study.observationLevelHierarchy: [
  {
    	levelName: 'plot',
	levelOrder: 1
  },{
    	levelName: 'plant',
	levelOrder: 2
  },{
    	levelName: 'block',
	levelOrder: 0
  }
]
  

observationUnit.observationLevels: [
  {
   	levelName: 'plot',
	levelOrder: 1,
	levelCode: 'plot_328A'
  },{
    	levelName: 'plant',
	levelOrder: 2,
	levelCode: '223'
  },{
	levelName: 'block',
	levelOrder: 0,
	levelCode: '1'
  }
]
```
