### ISSUE TITLE
Study Layout field "entryType" should be an enum and clearly defined

### ISSUE THREAD

**Issue by BrapiCoordinatorSelby** [plantbreeding/API#325]
from @dauglyon 

> apirary used to have those tables of key meanings but that info is gone in the docs now and one doesnt know, for example, what the enum for `entryType` is. It’s also a bit tricky to find inn swagger but such is life

from @BrapiCoordinatorSelby 
> you make a good point about the tables in apiary, however your example is bad lol. "entryType" has never been defined in one of those tables. it is in the documentation text for /studies/dbid/layout which was introduces in v1.2

**Comment by dauglyon** [comment]
It _wasn't_ in the table but in david's-ideal-land would be 😛

**Comment by BrapiCoordinatorSelby** [comment]
I visted Davids-Ideal-Land sometime last year. It was a good trip, I brought back a table as a souvenir and I put "entryType" in it.
https://brapiphenotyping.docs.apiary.io/#reference/observation-units/get-observationunits/get-/observationunits
