### ISSUE TITLE
Align BrAPI and MIAPPE

### ISSUE THREAD

**Issue by BrapiCoordinatorSelby** [plantbreeding/API#327]
BrAPI is missing several required fields from the MIAPPE specification

**Comment by bedroesb** [comment]
https://docs.google.com/spreadsheets/d/1d2HyJddYJsVnTesPXcaflg9gqE8IA9a8SHCYIPTA_fQ/edit#gid=401088219

/brapi/v1/trials/{trialDbId} :

Add field: additionalInfo.description
Add field: additionalInfo.submissionDate
Add field: additionalInfo.publicReleaseDate

/brapi/v1/studies/{studyDbId}
Add field: statisticalDesign.description
Add field: statisticalDesign.type
Add field: observationUnits.description
Add field: growthFacility.description
Add field: growthFacility.type
Add field: additionalInfo.culturalPractices
Add field: dataLinks.version

/brapi/v1/germplasm/{germplasmDbId}
Add field: germplasmCoordinates.latitude
Add field: germplasmCoordinates.longitude
Add field: germplasmCoordinates.altitude
Add field: germplasmCoordinates.uncertainty
Add field: germplasmPreprocessing
Add field: seedSourceDOI
Add field: seedSourceCoordinates.latitude
Add field: seedSourceCoordinates.longitude
Add field: seedSourceCoordinates.altitude
Add field: seedSourceCoordinates.uncertainty
Add field: seedSourceDescription


Add field: plantStructureDevelopmentStage
Add field: sampleDescription
Add field :xref

**Comment by cpommier** [comment]
Switched to a new branch 'issue-327'
@PapoutsoglouE

**Comment by cpommier** [comment]
Avoid additional info in trial
