### ISSUE TITLE
list study summaries and study search both use same url

### ISSUE THREAD

**Issue by marieALaporte** [plantbreeding/API#33]
_From @nickmorales on October 19, 2016 13:38_

http://docs.brapi.apiary.io/#reference/study/list-study-summaries/search-studies
http://docs.brapi.apiary.io/#reference/study/search-studies/search-studies

Both calls use /brapi/v1/studies-search
Maybe these two can be consolidated? 

_Copied from original issue: plantbreeding/Documentation#36_

**Comment by marieALaporte** [comment]
_From @jackeblagare on October 19, 2016 14:1_

Yes. They're the same just categorized according to use case but then we're defining the calls not the possible use cases.

**Comment by marieALaporte** [comment]
_From @gcornut on October 21, 2016 13:17_

The list study summaries was meant to be a GET request and the search study is a POST request.

I'm not against removing the study summary list GET request, we only use the study search POST request.

**Comment by marieALaporte** [comment]
_From @mverouden on December 2, 2016 13:20_

Please do not remove the GET request for study summary list, it is very important for Reinhard and me. This call is the workhorse for my work in doing statistical analyses on field trial data.

**Comment by gcornut** [comment]
I guess we could rename the 'list study summary' as 'search studies' in the documentation so I woudl be clear that they are the same call but with two different querying method. Either using POST or using GET.
It would be just like the the germplasm search which also has the two methods

**Comment by mverouden** [comment]
I am also still missing the trialDbId optional query parameter in the "search studies" a.k.a. list study summaries call. SEE [Issue 41](https://github.com/plantbreeding/API/issues/41)
