### ISSUE TITLE
Allow to search observation units by level

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#350]
It might be somehow implemented but need to check if we can easily get all plant or plot or block level observations.

**Comment by bedroesb** [comment]
https://github.com/plantbreeding/API/tree/master/Specification/Phenotypes

V1.3 Is supporting it 
Get Observationunits [GET /brapi/v1/observationunits{?germplasmDbId}{?observationVariableDbId}{?studyDbId}{?locationDbId}{?trialDbId}{?programDbId}{?seasonDbId}{?observationLevel}{?observationTimeStampRangeStart}{?observationTimeStampRangeEnd}{?page}{?pageSize}]

**Comment by cpommier** [comment]
Now that you mention it, that's obvious. We should also check if it is easy to get all levels/assay for a study.
