### ISSUE TITLE
Germplasm Call -> donors array example inconsistency

### ISSUE THREAD

**Issue by netbofia** [plantbreeding/API#352]
I see that in the schema donors array should have 3 properties, when they exist.

Could you add it to the example in germplasm call? I had to look it up in the schema

```
donors:[
  donorAccessionNumber: "pt 001231",
  donorInstituteCode: "PRT034",
  germplasmPUI: "http://pui.per/accession/A000003"
]

```

**Comment by BrapiCoordinatorSelby** [comment]
see closing comment in #351 

This has been resolved in V2.0
