### ISSUE TITLE
Inconsistent call API/studies get v1.3

### ISSUE THREAD

**Issue by netbofia** [plantbreeding/API#353]
/studies [example:](https://github.com/plantbreeding/API/tree/V1.3/Specification/Studies#studies-brapiv1studies) 
 - Remove property or add deprectate statement for:
       - name
       - studyType

According to [this schema:](https://github.com/plantbreeding/API/blob/V1.3/Specification/Studies/Schemas/study.yaml)
  - studyType is deprecated in favor of studyTypeName
  - name doesn't appear in this schema

[This schema:](https://github.com/plantbreeding/API/blob/V1.3/Specification/Studies/Studies_GET.yaml) Still has name and studyType

The provided [example:](https://github.com/plantbreeding/API/tree/V1.3/Specification/Studies#studies-brapiv1studies) doesn't list:
 - datalinks
 - lastupdate
 - license
Which are listed in [this schema](https://github.com/plantbreeding/API/blob/V1.3/Specification/Studies/Schemas/study.yaml).

Are they part of v1.3?

**Comment by BrapiCoordinatorSelby** [comment]
In this case, you are dealing with two schemas, 'study.yaml' and 'studySummary.yaml'

`GET /search/studies/{searchID}` and `GET /studies` both return a studySummary object which is smaller and does not contain `datalinks`, `lastupdate`, `license`, etc. 

`GET /studies/{studyDbId}` returns a study object which has all the details connected with a study.

This also explains some of the `name` and `studyType` issues you were seeing in the examples (though the example responses are not always reliable in 1.3). Back in V1.1/1.2, study had a field `name` but studySummary had a field `studyName`. This was resolved in 1.3 by making everything `studyName`, but it looks odd when looking for the deprecated history.


In V2.0, there are no summary objects and there is one and only one schema for defining each kind of BrAPI entity. Example responses, in most cases, will also be generated from those schema definitions and will not need to be maintained separately.
