### ISSUE TITLE
MCPD

### ISSUE THREAD

**Issue by mobreza** [plantbreeding/API#354]
How much of the https://brapi.docs.apiary.io/#reference/germplasm/germplasm/get-germplasm-mcpd-by-germplasmdbid is based on Genesys API?

**Comment by BrapiCoordinatorSelby** [comment]
It was based entirely on the Bioversity MCPD v2.1 spec
https://www.bioversityinternational.org/fileadmin/user_upload/online_library/publications/pdfs/FAOBIOVERSITY_MULTI-CROP_PASSPORT_DESCRIPTORS_V.2.1_2015_2020.pdf

I was not aware that Genesys had an API which handled the same thing. Do you know who would be the best person to talk to to try to standardize?

**Comment by mobreza** [comment]
@BrapiCoordinatorSelby I just found it interesting that the groups tally up with the JSON Genesys used for several years (https://www.genesys-pgr.org/doc/0/apis) just using better names. I figure it's sensible to use if it showed up in two different projects.

We can try to synchronize the names. Our current ones are in https://gitlab.croptrust.org/genesys-pgr/genesys-ui/blob/master/src/model/accession/Accession.ts and related classes.

**Comment by BrapiCoordinatorSelby** [comment]
Closing this issue. If there is any further action needed, please reach out to me.
