### ISSUE TITLE
Implementation of a top level  /brapi call for installation metadata

### ISSUE THREAD

**Issue by RichardBruskiewich** [plantbreeding/API#356]
There doesn't  seem to  be  a consistent way  of  reporting high-level  information about a BrAPI  site.   

There is at least one example - https://www.crop-diversity.org/mgis/brapi/v1/ -  which give s such metadata, but this doesn't seem to be standard practice,  and  is both repetitive  in that it  reports the release number  -  1.2 - a minor version of  v1. 

Having,  say, a top-level **brapi/info**  call  to document top-level  metadata about a BrAPI  compliant provider implementation could be a better way of  reporting  such  information which includes:

1) expose installation name, owner, contact details, etc.
2) documenting BrAPI version support (v1, v1.3,  v2,  etc)

This would facilitate management of major versioning.

Open questions: 

1) should  the **/brapi/v#/calls** be  moved up  (or not) to this level?
2) should the  minor  version  still be  reported  on the root of the major  version  path, I.e. under  **/brapi/v1/**  as  above?

**Comment by raf64flo** [comment]
I was about to create an issue in the same idea.

Adding a global endpoint returning the exact BrAPI version implemented by a server without having to look at each endpoint specifically could simplify the usage of the API.

Ping @cpommier

**Comment by BrapiCoordinatorSelby** [comment]
I have a couple problems with this request.
* First, any "global" endpoint which is defined at the BrAPI root (`/brapi/`) is un-versioned by definition. An un-versioned endpoint can never be changed or updated without risk of breaking other systems that rely on that API. This is in general a bad practice.
* Second, defining a minor version for the whole server may be simpler and helpful, but not always realistic. There are several teams who have mixed minor versions of BrAPI and rely on different versions simultaneously. There may be many reasons for this such as support for legacy systems or lack of development time/resources. A server might have `/germplasm` implemented for V1.1, but then they need to add support for a new BrAPP using `/studies` from V1.3. I haven't done a formal poll, but I would bet most systems could not claim to have a pure, single version of BrAPI support. 

That said, in BrAPI-Core V2.0 I have added `/brapi/v2/serverinfo` which has replaced the old `/calls` endpoint. `/serverinfo` has fields for server description and contact information, but no server level version tag.

@RichardBruskiewich @raf64flo please check out the new endpoint to see if it is acceptable. For now I will close this issue, feel free to re-open if you would like to see more changes.
