### ISSUE TITLE
Add all /observationunit/ return fields in /studies/{studydbid}/observationunit

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#357]
Some fields are missing, like :
- "treatments", 
- "observationlevels"
- maybe otherthings are missing

**Comment by cpommier** [comment]
Additions to Studies_StudyDbId_Observationunits_GET_POST_PUT.yaml

**Comment by cpommier** [comment]
Seems ok, merge request submitted

**Comment by BrapiCoordinatorSelby** [comment]
BrAPI V2.0 has removed `GET /studies/{studydbid}/observationunit` and replaced it with `GET /observationunits?studyDbId={studyDbId}`
The `ObservationUnit` schema will be used for all responses of `/observationunits` making them all consistent.
