### ISSUE TITLE
A mechanism for handling asynchronous requests

### ISSUE THREAD

**Issue by philipglaser** [plantbreeding/API#36]
Hi folks, 

I just created pull request https://github.com/plantbreeding/API/pull/35. 

The change I propose was discussed during the workshop today amongst myself, Lukas, Iain, and Gordon. The use case in question is that we want Flapjack to retrieve matrix data from GOBII through allelematrix-search so that it can do its visualization magic on the data. In GOBII, however, matrix extraction is handled asynchronously: a client calls a webservice that creates an instruction file that is seen by a chron job running on the file server that performs the extraction. We've worked out the choreography of everything in this scenario, but cannot find a way to handle tracking the status of the submitted request in the existing specification.

I should mention that one proposal for dealing with the problem in the current spec was to use HTTP status codes. That is, the allelematrix-search could specify a file in the datafiles array; if a GET on the file gives a 404, you know it isn't done. There are a few problems with this approach: 

- In the case of GOBII, file transfers do not go through the web request/response cycle because this method of retrieving large files consumes valuable process space in the web server; the file transfer can be more efficiently and reliably handled through FTP; 
- It leaves the process open to race conditions: it is easily imaginable that a file could appear to be present while it is in the process of being copied -- the results in this scenario would be an impartial data extract. 

I think my proposed wording does justice to our discussion. I did however find myself differing with Iain on the point in the process at which the path to the result must be provided: the name of the directory or file may only be known when the process is completed, and so the file path should not be required in the response until the process is complete.

One point we agreed on is that we do not anticipate that this change will break existing functionality: new status codes and new resources are proposed, but there no changes to the structure of existing calls. 

Thanks!
--Phil

**Comment by BrapiCoordinatorSelby** [comment]
#35 Accepted and merged, closing issue
