### ISSUE TITLE
Strictly Define Summary Objects (v2.0?)

### ISSUE THREAD

**Issue by dauglyon** [plantbreeding/API#361]
In situations where a summary of an object is embedded in the response of another object:
```
// parent object
{
  parentID: "foo",
  listOfObjects: [
    {embeddedObjectID:"bar1",...},
    {embeddedObjectID:"bar2",...}
  ],...
}
```
It should somehow be made clear that it _is_ a summary, and there should be a standard form for that summary. Ideally, any summary of the same type of object should be of the same form.

**Comment by BrapiCoordinatorSelby** [comment]
No more summary objects and very few un-paginated lists within responses in V2.0.
I believe the Studies / Observation Units relationship was the inspiration for opening this issue originally. The Study object no longer has a list of Obs Units in the response. The client must make a second query for Obs Units by StudyDbId.
If there are specific cases in V2.0 that need special attention, please open a new issue.
