### ISSUE TITLE
Should sample creation  be a 'POST' rather  than  a  'PUT' operation?

### ISSUE THREAD

**Issue by RichardBruskiewich** [plantbreeding/API#368]
See  https://github.com/plantbreeding/API/blob/V1.3/Specification/Samples/Samples_GET_PUT.yaml.

Purist HTTP would  say  that  to creation of a sample as a REST  resource should be a 'POST' operation, not a 'PUT'?

**Comment by vg249** [comment]
I agree. PUT is mostly used when you can be identify a resource by an ID, either for creating or update.
In my case, When I am creating a list of samples for a particular project, I am creating the resources and generating the resource ID. It would make more sense if it is a POST operation.

**Comment by BrapiCoordinatorSelby** [comment]
Done in BrAPI-Genotyping V2.0
ee1078f0b08274355caf9c3bf7a3aa724746941b

I'm following this pattern for most entities
`GET /entity` -> sends query parameters -> returns filtered list
`POST /entity` -> sends array of new entity -> returns list of entities sent
`GET /entity/{DbId}` -> sends DbId -> returns exact entity
`PUT /entity/{DbId}` -> sends updated entity -> returns updated entity
