### ISSUE TITLE
Keeping the data key in all cases

### ISSUE THREAD

**Issue by philipglaser** [plantbreeding/API#37]
Hi folks, 

Another discussion that Lukas, the JHI folks, and I shared touched on the data key in the result object. As Java developers, Iain, Gordon, and I were looking for a way to use type-parameterized classes so that we could have a single Java response object that could be reused for all of the possible response data. It is possible to do this if all data are only returned in the data array. However, I came to understand that having a data object as a direct child of the result object in addition to the data array is an important feature of the API, as it allows for this parent object to serve as meta data for the data array. I also see that this idiom is useful for any situation in which you have a master-detail data scenario. 

Still, it would be useful from an implementation perspective for the data array to _always_ be present even in cases where the direct child of the result object could stand on its own. No one in the group raised any objections to this idea, so I am proposing it here formally. 

There was also some discussion about the content of the pagination object: I think it was suggested that the pagination should always be 0 when there are no data items. I hope to have captured the essence of that discussion -- please correct me if I've gone astray here. 

The relevant paragraph of the README is as follows: 

> The payload data is contained in a key called "result", containing an object with the response. If there is a paginated response, a "data" key will be present, with a list value, which will be paginated over (showing pageSize elements of the currentPage).

I propose to reword this paragraph as follows:
> The payload is contained in a key called "result." The "result" key contains a key named "data," which is an array of data items. The "result" key may also contain a child object with any number of arbitrary keys. If the data key array is populated, the pagination key of the metadata object will describe how it is segmented. When the data key is an empty array, all values of the pagination object have the value of 0. There are responses in which the only data in the response is in the data array. Some responses have neither a data array nor a child object (e.g., the status resource on the allelematrix-search call). 

Many thanks!
--Phil

**Comment by lukasmueller** [comment]
This makes total sense to me, but should be discussed for version 2 as per discussion in BrAPI meeting in Montpellier.

**Comment by philipglaser** [comment]
In our discussion it occurred to me that there is a way to make the presence of the "master" object easier to manage in a typed language implementation. If the master object were the value of another key under **result** rather than a direct child of **result**, a language like Java could type-parameterized not only the list items, but also the master key item. For example, a response could be

```
{
   "metadata":{
      "pagination":{
         "pageSize":0,
         "currentPage":0,
         "totalCount":0,
         "totalPages":0
      },
      "status":[

      ],
      "datafiles":[

      ]
   },
   "result":{
      "master":{

      },
      "data":[

      ]
   }
}
```

**Comment by barrow-wight** [comment]
Plus 1

**Comment by BrapiCoordinatorSelby** [comment]
I am closing this old issue without changes to the specification for the following reasons.

1.  The original problem was how to create a single object in Java which can act as a wrapper for all BrAPI responses. The compromise solution to this problem (discussed 1 on 1 with Phil) is to create 2 wrapper objects, one with `data` array and one without, then use Type Generics to include the specific data elements.
2.  Now that BrAPI is strictly defined in the OpenAPI 3 standard, Java code can be generated to create all the model objects needed. This will give a specific class for each type of JSON response, but they do not need to be created by hand, so the time savings of a generic wrapper class is less necessary.
3.  An alteration to the core of how BrAPI works would be a big change for not much reward. 

If you feel this is still an important issue which should be addressed, please contact me, or open a new issue with details of the specific difficulty you are faced with.
