### ISSUE TITLE
PUT /studies/{studyDbId}/observationunits

### ISSUE THREAD

**Issue by peterrosario** [plantbreeding/API#374]
I am creating the Request body from the GET /studies/{studyDbId}/observationunits Response.  The Response has multiple observations.  The Request has multiple observations.  Each Request observation has these fields: germplasmDbId, germplasmName, observationLevel, observationUnitDbId, observationUnitName, operator, studyDbId, and uploadedBy.

It is not clear to me how I am to populate the Request observation fields listed above from the Response observations.  I suppose I could use the Response to populate germplasmDbId, germplasmName, observationLevel, observationUnitDbId, observationUnitName, and studyDbId but is this correct?

How should operator and uploadedBy be populated.  Is the Response observation's collector field the source for the Request observation's operator field or the uploadedBy field or both or neither?

**Comment by BrapiCoordinatorSelby** [comment]
Issue Triage Notes: 
GET responds with "observationSummary" objects, but the PUT is expecting "observation" objects and there is a discrepancy between these two objects. This discrepancy needs to be resolved. 

> I suppose I could use the Response to populate germplasmDbId, germplasmName, observationLevel, observationUnitDbId, observationUnitName, and studyDbId but is this correct?

Yes

>How should operator and uploadedBy be populated. Is the Response observation's collector field the source for the Request observation's operator field or the uploadedBy field or both or neither?

I believe the original intention was "operator" = "collector" and "uploadedBy" was reserved for the person adding the data to the database. So you have many field data collectors but maybe only one data manager. 
If you don't have a seperate user identifier to populate "uploadedBy" you could leave it blank, or copy "operator". Either is acceptable as far as I'm concerned, but different servers may have created their own rules around this.

**Comment by BrapiCoordinatorSelby** [comment]
Latest commits on V2.0 branch have resolved this discrepancy.
