### ISSUE TITLE
Inconsistency with lists of key value pairs?

### ISSUE THREAD

**Issue by philipglaser** [plantbreeding/API#38]
Hi, 

The response from studies-search is a list of items as follows: 

`{
                "studyDbId": 35,
                "name": "Earlygenerationtesting",
                "trialDbId" : 1,
                "trialName" : "InternationalTrialA",
                "studyType": "Trial",
                "seasons": ["2007 Spring", "2008 Fall"],
                "locationDbId": 23,
                "locationName": "Kenya",
                "programDbId": 27,
                "programName": "Drought Resistance Program A",
                "startDate": "2007-06-01",
                "endDate"  : "2008-12-31",
                "studyType": "Trial",
                "active" : "true",
                "additionalInfo" : {
                    "property1Name" : "property1Value",
                    "property2Name" : "property2Value",
                    "property3Name" : "property3Value"
                }
}`

The additionalInfo object is an object of arbitrary key-value pairs. However, the status collection is an _array_ of indivudal key-value objects. Wouldn't it make sense to standardize on one idiom or another? "

Thanks. 
--Phil

**Comment by lukasmueller** [comment]
I think the information provided by the two keys are somewhat different. In the case of additionalInfo, we just want to provide additional key value pairs. In the case of status, we want to provide a list of code/message entries that belong together, which is a list of objects.
