### ISSUE TITLE
Trial Publications inconsistency 

### ISSUE THREAD

**Issue by netbofia** [plantbreeding/API#382]
There is an inconsistency between Get Trials and Get TrialsById calls for publications attribute:
Is this on purpose?

in TrialsById:
```
"publications": [
     {
            "publicationPUI": "doi:10.15454/312953986E3",
            "publicationReference": "https://brapi.org"
      }
],
```

while in Get Trials:
```
"additionalInfo": {
    "donorName": "Donor1",
    "publications": "doi:10.2345/GEZG3T23535",
    "specialProject": "Project1"
},
```

**Comment by netbofia** [comment]
Fix this by adopting DF's solution of creating a new Table Publications with this info. 
Copy all publication info from additionalInfo to this new table.

**Comment by BrapiCoordinatorSelby** [comment]
BrAPI V2.0 corrects this inconsistency (and many similar ones). There is now 1 defined `Trial` object in BrAPI and any call that returns a trial returns the same set of fields.
