### ISSUE TITLE
StudiesApi.studiesStudyDbIdObservationunitsZipPost() Documentation . . .

### ISSUE THREAD

**Issue by peterrosario** [plantbreeding/API#383]
. . . is not enough to explain how to use this method.  The issue is the java.lang.Object body parameter.  I presume this is somehow the zip file.

Also, the documentation discusses observationUnitDbId and observationDbId but these are not method parameters.  Are they inside the zip file/body parameter?

**Comment by BrapiCoordinatorSelby** [comment]
There was a piece of documentation which was lost over time
>In case where JSON data is zipped for faster transfer speed (as in the case of the IRRI handheld implementation), the zipped JSON file will be listed in datafiles. The zipped file contains a JSON file with the same structure as the BrAPI call. In this case a format parameter should be passed as well.
[BrAPI V1.0](https://brapiarchive10.docs.apiary.io/#reference/study/observation-unit-details/save-observation-unit-phenotypes)

The original intention was to produce a JSON file, put that file inside a ZIP, then send the ZIP as a byte stream to be unpacked by the server. `observationUnitDbId ` and `observationDbId ` were to be fields in that JSON file. Nowadays, client and server can both be configured to automatically send compressed messages, with the HTTP header `Content-Encoding: gzip` and dealing with files on disk is no longer necessary.

Unless it is specifically requested, I would avoid implementing this call. I'm honestly not sure how it survived in the BrAPI spec this long, I guess I just got used to it being there and never questioned it. In BrAPI V2.0, it is already gone.
