### ISSUE TITLE
Add seeLot to Germplasm and ObservationUnit

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#384]
The new seedLot added to brapiV2 will be very usefull and we propose to push its integration in other call a bit further. The link with observationUnit and germplasm could be stronger:

Germplasm:
GET /brapi/v1/germplasm/{germplasmDbId}/seedLot

ObservationUnit:
In the reponse structure add: seedLot

We could also consider renaming seedLot to Lot. Indeed, a seedLot can be a tree/grape cutting or any non seed way to reproduce a germplasm.

What do you think ?

**Comment by cpommier** [comment]
ping @aliceboizet @mbuy @bilalelhoudaigui

**Comment by BrapiCoordinatorSelby** [comment]
I can make those connections to germplasm and observationUnit. I will close this issue when its done.

I kinda think `/lot` is a little too generic, the word has too many different meanings. I will add to the documentation an explanation that `seedLot` can represent more than seeds. And the object contains a field `units` to describe the type of thing actually stored in the seed lot.

If anyone has suggestions for alternative names, please share

**Comment by cpommier** [comment]
Looks good @aliceboizet ,  no?
