### ISSUE TITLE
get /studies/studyDbId/germplasm plus  GET /studies/germplasm?studyDbId=

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#385]
As discussed in #369 there is a need to have /studies?studyDbId=

But then what about all the /studies/studyDbId/germplasm|observationUnit|observationVariable|... calls ?
We could have the following solution:
/studies/germplasm|observationUnit|observationVariable?studyDbId={studyDbId}

What do you think ?
We are evaluating the impact on some of our tools.

**Comment by cpommier** [comment]
ping @mbuy @aliceboizet @bilalelhoudaigui

**Comment by BrapiCoordinatorSelby** [comment]
In BrAPI V2.0 I've tried to address this by mostly removing nested call structures. 
So `/studies/{studyDbId}/germplasm` is replaced with `/germplasm?studyDbId={studyDbId}` and all similar calls follow this pattern (observations, observationUnits, observationVariables, etc)
This allows for more flexibility without loss of functionality, and it better aligns the response objects. So `/germplasm` will return the same type of objects whether or not you filter by studyDbId.

Thoughts?
