### ISSUE TITLE
Possible Bug - Swagger generated nodejs Server does not start

### ISSUE THREAD

**Issue by coeit** [plantbreeding/API#395]
When trying to generate a nodejs Server with the [swagger editor](https://editor.swagger.io/), using the API provided on [swaggerhub](https://app.swaggerhub.com/apis/PlantBreedingAPI/BrAPI/1.3#/polygon) (I exported the API as JSON/YAML and uploaded the file to the Editor), I get the following `Invalid version` Error when trying to use `npm install` or `npm start` for the generated nodejs server:
`npm install`:
```
npm WARN Invalid version: "1.3"
```
`npm start`:
```
npm ERR! Invalid version: "1.3"
```
This happens for both BrAPI v1.2 and 1.3 on nodejs `v12.13.0`

**Comment by BrapiCoordinatorSelby** [comment]
This is a little inconvenient, but not a bug. Node requires the version number to follow the rules of Semantic Versioning, but the BrAPI version number does not do this. In your `package.json` file, change the version to "1.3.0" and it should let you run it. 

I was able to run `npm start` without issue, but the app starts and immediately stops. It looks like some issues with some required libraries, `connect` and `oas3-tools` seemed to be causing trouble. So index.js might need some editing before it will run properly. 

Remember that the swagger generated servers are good starting points, but they need work to be fully functional.

**Comment by coeit** [comment]
Thank you for the quick response.
I was able to start the server by changing the BrAPI version number in the `package.json` to `1.3.0` as you suggested and also changing `openapi: 3.0.0` to `openapi: 3.0.1` in the generated `swagger.yaml`. This solution was suggested on [Stackoverflow](https://stackoverflow.com/questions/55711019/node-js-server-generated-automatically-doesnt-start-swagger-openapi).
