### ISSUE TITLE
Inconsistent call API/Specification/Studies/ObservationUnitDetails.md

### ISSUE THREAD

**Issue by mverouden** [plantbreeding/API#40]
This GET call is defined as  [/brapi/v1/studies/{studyId}/observationunits?observationLevel={observationLevel}] shouldn't it be Observation Unit Details [/brapi/v1/studies/{studyId}/observationUnits?observationLevel={observationLevel}]?

The JSON output is specified as:
{
    "metadata" : {
        "pagination": {
            ...
        },
        "status" : [],
        "datafiles": []
    },
    "result" : { 
        "data" : [
            {
                "observationUnitDbId": "abc-123",
                "observationUnitName": "Test-2016-location-34-575",
Here Unit is also capitalized.

**Comment by lukasmueller** [comment]
I think the URLs are usually completely in lower case, only the parameters are in CamelCase. So in this case, "observationunits" is part of the URL, so it should be lowercase.
