### ISSUE TITLE
Inconsistency in study with contact 

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#401]
The following :       contacts:
          description: List of contact entities associated with this study
          items:
            $ref: '#/components/schemas/Contact'
Refers to components/schemas/Contact' butwe can find only people in brapiCore, not contact

**Comment by BrapiCoordinatorSelby** [comment]
`Contact` is shared between Trials and Studies, so the class definition is under `Trials/Schemas`

the `$ref` term identifies the path within the final compiled YAML file, not a real physical path. As long as the `Contact.yaml` file exists somewhere under the Core module, anything in Core will be able to see it. SwaggerHub and Apiary show the final compiled YAML, after all the merging and linking of classes.
