### ISSUE TITLE
Can we have a reference to the MCPD correspondence too?

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#404]
https://github.com/plantbreeding/API/blob/eae9433880153c7d0f87509126a9fd72800b9bec/Specification/BrAPI-Germplasm/Germplasm/Schemas/GermplasmNewRequest.yaml#L162

**Comment by BrapiCoordinatorSelby** [comment]
I'm not exactly sure what you mean here? can you elaborate please?
