### ISSUE TITLE
Low consistency in attribute naming

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#405]
https://github.com/plantbreeding/API/blob/eae9433880153c7d0f87509126a9fd72800b9bec/Specification/BrAPI-Germplasm/Germplasm/Schemas/GermplasmNewRequest.yaml#L133
Should we have all attributes named germplasmeName or simply name ? 
Ideally, we should apply the same attribute naming convention everywhere.

**Comment by BrapiCoordinatorSelby** [comment]
The general attribute naming scheme I've been following is to make the attributes as short as possible, without prefex's, UNLESS there is a naming conflict. So common attributes like ...DbId, ...Name, ...PUI, etc, all get prefex's, but attributes specific to that object generally do not. 
There is a lot of gray area in this rule, and there will probably always be exceptions, but it provides a general guideline to follow.

That said, I cleaned up GermplasmNewRequest.yaml to actually follow that rule
