### ISSUE TITLE
XREF or Synonym IDs ?

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#406]
https://github.com/plantbreeding/API/blob/eae9433880153c7d0f87509126a9fd72800b9bec/Specification/BrAPI-Germplasm/Germplasm/Schemas/GermplasmNewRequest.yaml#L191

**Comment by BrapiCoordinatorSelby** [comment]
I think both may be necessary. Germplasm have Synonyms which are human readable names all referring to the same thing. You might maintain a list of them defined by different users on a single database. Xref's was meant to be an external reference to an outside source. 

That said, this question has reminded me to do a review of Xref usage in BrAPI ... its a small mess, I'll see what I can do to clean it up
