### ISSUE TITLE
Consider using the location object for GermplasmOrigin

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#408]
https://github.com/plantbreeding/API/blob/eae9433880153c7d0f87509126a9fd72800b9bec/Specification/BrAPI-Germplasm/Germplasm/Schemas/GermplasmOrigin.yaml#L1

For the sake of consistency, , it should be considered weither to use those direct MIAPPE field or use the location object, in a MIAPPE compliant flavor.
It's a complicated dilemma.

**Comment by BrapiCoordinatorSelby** [comment]
This really depends on how important these three fields are: `latitudeDegrees`, `longitudeDegrees` and `coordinateUncertainty`. 
Option 1: We drop the `...Degrees` fields, then it is a good fit for a GeoJSON object to represent coordinates, keep `altitude` and `coordinateUncertainty`.
Option 2: Replace `GermplasmOrigin` with a `Location` object OR reference to a `LocationDbId`. This would effectivly get rid of  `latitudeDegrees`, `longitudeDegrees` and `coordinateUncertainty`.
Option 3: Leave as it is

Option 2 seems to me like a big unnecessary change, Option 1 I could be talked into as it would be another place to standardize global coordinate info as GeoJSON, and the overall impact would be small. Option 3 is obviously the easiest, but it also maintains those extra fields, if they are necessary. I'm not sure of their original purpose or if it is still important to maintain the  `...Degrees` fields. You should be able to translate between decimal and degrees on the fly if needed.

**Comment by BrapiCoordinatorSelby** [comment]
Spoke with Cyril in person. Going with Option 1 unless others have comments

**Comment by jeback1** [comment]
Will altitude be as described here: [](http://wiki.geojson.org/RFC-001#Specification) , specifically:
'coordinates' - A coordinate consists of an array of two or three number values representing x, y, and optionally z.

**Comment by raf64flo** [comment]
> Will altitude be as described here: http://wiki.geojson.org/RFC-001#Specification , specifically:
> 'coordinates' - A coordinate consists of an array of two or three number values representing x, y, and optionally z.

The referenced spec is deprecated, please prefer to use published RFC such as: https://tools.ietf.org/html/rfc7946

Especially [section 3.1.2](https://tools.ietf.org/html/rfc7946#section-3.1.2)

**Comment by jeback1** [comment]
Ok, seems like the definition of coordinate remains the same.  From 3.1.1: " A position is an array of numbers.  There MUST be two or more elements.  The first two elements are longitude and latitude, or easting and northing, precisely in that order and using decimal numbers.  Altitude or elevation MAY be included as an optional third element."

**Comment by BrapiCoordinatorSelby** [comment]
@jeback1 You are correct and I just read the same thing. 
I will modify the documentation for the BrAPI GeoJSON object to include elevation/altitude as described in the RFC.
Then we can replace most of the fields in germplasmOrigin with GeoJSON
