### ISSUE TITLE
Extra query parameter in List Study Summaries

### ISSUE THREAD

**Issue by mverouden** [plantbreeding/API#41]
When using the List Study Summaries [/brapi/v1/studies-search?studyType={studyType}&seasonDbId={seasonDbId}&locationDbId={locationDbId}&programDbId={programDbId}&germplasmDbIds={germplasmDbIds}&observationVariableDbIds={observationVariableDbIds}&pageSize={pageSize}&page={page}&active={active}&sortBy={sortBy}&sortOrder={sortOrder}] it would be very useful to also include trialDbId as optional parameter.

When I know the trialDbId I would like to obtain summaries of all studies in this trial. I remember in Ithaca we defined a trial to contain multiple studies please also check [Field data breakout session Ithaca](https://github.com/plantbreeding/Documentation/wiki/Field-data-collection-and-Data-analysis-review-of-Brapi-calls). Therefore I believe addition of this additional parameter makes sense.

**Comment by lukasmueller** [comment]
Great suggestion. Since this is a small change, maybe we can put this in version 1.0?
