### ISSUE TITLE
Dead documentation link in github Response_Structure.md

### ISSUE THREAD

**Issue by jeback1** [plantbreeding/API#419]
This page [https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Response_Structure.md
](https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Response_Structure.md
) has a link : (https://github.com/plantbreeding/documentation/wiki/Best-Practices-and-Conventions) that lands on an error message.

**Comment by BrapiCoordinatorSelby** [comment]
Fixed
Points to the BrAPI Wiki now
