### ISSUE TITLE
JSON-LD

### ISSUE THREAD

**Issue by mrouard** [plantbreeding/API#42]
Hi,

Should we consider JSON LD for version 2?
http://json-ld.org/

**Comment by barrow-wight** [comment]
I think its something that should be seriously considered.

**Comment by c5sire** [comment]
I agree.

**Comment by bebertpalu** [comment]
Propose a JSON LD is very important for the future for interconnecting the data and give more semantic. 
why : e.g 

First data:
{
  "@context": "http://schema.org/",
  "@type": "gene",
  "chromosome": "1",
  "name": "AT1G01010",
  "start position": "3631",
  "ontologie": "NCBITaxon_3702",
  "url": "http://identifiers.org/ensembl.plant/AT1G01010"
}

Seconde data

{
  "@context": "http://schema.org/",
  "@type": "gene",
  "chromosome": "1",
  "name": "Os01g0100100",
  "start position": "2983",
  "ontologie": "NCBITaxon_3702",
  "url": "http://identifiers.org/ensembl.plant/AT1G01010"
}

We can imagine i want all gene in chromosome 1 who are between start position 1000 and 4000
it easy when the data are in jsonLD or other format of language of web semantic.

https://www.w3.org/2013/dwbp/wiki/RDF_AND_JSON-LD_UseCases

**Comment by gcornut** [comment]
Hi everyone, 

I'm commenting this issue to share our experience with **BrAPI phenotyping linked data**.

In the last couple of months, we have been experimenting with JSON-LD in the following repository:  [plantbreeding/BrAPI-jsonld](https://github.com/plantbreeding/BrAPI-jsonld)

For a project of ours we decided to use JSON-LD as an intermediary format between BrAPI JSON and RDF. We have developped a [python ETL script](https://github.com/gnpis/BrAPI-extract-index-prototype) that can extract phenotyping data from a **normal BrAPI endpoint**, transform data into RDF and load it into an RDF triple store.

Our approach to BrAPI RDF was to create an unofficial [BrAPI OWL model](https://github.com/gnpis/BrAPI-extract-index-prototype/blob/master/linked-data/pheno-brapi-model.owl) describing the BrAPI entities and attributes. Then we used JSON-LD to map BrAPI JSON attributes & entities to BrAPI OWL model attributes & entities and just converted the resulting JSON-LD to RDF. One of the big requirements for JSON-LD was to get URI for **every BrAPI entities**. For our project we decided to use the URI we already had (on germplasm and some variables) and generate URIs when needed. The generated URIs are almost always valid BrAPI calls with the following format: ```{server}/brapi/v1/{entity_name}/{id}``` 

As a result of all of this, we now expose [an entire Wheat phenotyping network dataset in Virtuoso](https://urgi.versailles.inra.fr/sparql?qtxt=PREFIX+brapi%3A++%3Chttps%3A%2F%2Fbrapi.org%2Frdf%2F%3E%0D%0ASELECT+%3Fnetwork+%3Fstudy+%3Fattribute+%3Fvalue+%0D%0AFROM+%3Curn%3Aurgi%3Apheno-brapi-inra-small-grain-cereals-network%3E%0D%0AWHERE+%7B%3Fstudy+a+brapi%3AStudy%3B%0D%0A++++++++++++++%3Fattribute+%3Fvalue.%0D%0A+++++++%3Ftrial+a+brapi%3ATrial%3B%0D%0A++++++++++++++brapi%3AhasName+%3Fnetwork.%7D%0D%0AORDER+BY+%3Fnetwork+%3Fstudy&format=text%2Fhtml&timeout=0&debug=on). This link will get you on the Virtuoso SPARQL query editor with an example query that lists all of the phenotyping studies of the dataset with all of their attributes. The dataset contains BrAPI studies, trials, locations, observation units, observations and programs.

In the future, we want to develop a BrAPI OWL model that would integrate other ontologies like MIAPPE, CropOntology, Multicrop passport, etc. This approach could bring more **data interoperability** (with ontology crosslinking), **validation and reasoning** (with rule definitions)

**Comment by gcornut** [comment]
I've created an V2 proposition for JSON-LD in BrAPI. 
I'm closing this issue to focus on the concrete proposition
https://github.com/plantbreeding/API/issues/192
