### ISSUE TITLE
Create Post - /search/observationunits/table ? to generate data matrices with one observationUnit by line

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#421]
/search/observationunits/ seems more powerfull than /observationunits/table (more search parameters).
/observationunits/table seem to cover curent use cases, but do we need to provision /search/observationunits/table ?

plus

Brapi V2 enforce one observationUnit then an observation call for the actuall value.
Can /table solve this ?
An observationUnitWithObservation call ?

**Comment by cpommier** [comment]
Use case : I want tabular data for trial X and germplasm 1 to 100

**Comment by cpommier** [comment]
Relation between year and season ?

**Comment by BrapiCoordinatorSelby** [comment]
Notes concerning .../tables structure.

 - Observation Levels needs to be expanded to include a variable number of levels as column headers.
 - /observationUnits/table can have optional time stamp columns next to each variable column. this is handled as an extra pseudo variable named "<observationVarialbleName> Timestamp". This does not change the JSON structure, but needs to be documented.

**Comment by cpommier** [comment]
Conclusion Peter and I:
- stick to search/observationUnits with an additional parameter "includeObservations". This allows to fall back to v1.3 approach on demand. This implies that the client accept to lose pagination on observations.

- For the future, if time series or number of observation by observation unit gets too important: generate tables with two parallel calls : /search/observationUnit & /search/observations then reconstruct the matrix in memory (see observationunits/table for an interesting dic to do this)
