### ISSUE TITLE
Non standard Level hierarchy not possible in BraPIv2

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#422]
https://github.com/plantbreeding/API/blob/d676187253e952648b68953b2486a66ff75e98e1/Specification/BrAPI-Phenotyping/ObservationUnits/Schemas/ObservationUnitNewRequest.yaml#L44

In the current version, there is a loss of funcitonality. Indeed, it was possible to add the following informaiton to onbservationsUnits : `replication:3, plot:pl34a ,  individual : qtrzet` or `rep : 1 , bloc : 25 , individual : 3456`
This is no longer possible now. We need to have up to 5 levels with a level name hierarchy specific of each study.
It was handled by :

        "observationLevels": "block:1;plot:1"

**Comment by cpommier** [comment]
Adding such a field in aditional info but troublesome for the interface handling:https://urgi.versailles.inra.fr/ephesis/ephesis/viewer.do#dataResults/trialSetIds=22

**Comment by cpommier** [comment]
We could also have a fixed hierarchy up to 5 plus display names:
```
level1, level2, level3, level4, level5
level1displayName, level2displayName,, level3displayName,, level4displayName,, level5displayName,
```
or 
```
rep, block, subblock, plot, plant
repDisplayName, blockDisplayName, subblockDisplayName, plotDisplayName, plantDisplayName
```

**Comment by BrapiCoordinatorSelby** [comment]
Related #324

**Comment by cpommier** [comment]
MIAPPE level list : study, block, sub-block, plot, sub-plot, pot, plant
Extendable if needbe

**Comment by BrapiCoordinatorSelby** [comment]
Proposal

```
study.observationLevelHierarchy: [
  {
	levelName: 'plot',
	levelOrder: 1
  },{
	levelName: 'plant',
	levelOrder: 2
  },{
	levelName: 'block',
	levelOrder: 0
  }
]
  

observationUnit.observationLevels: [
  {
	levelName: 'plot',
	levelOrder: 1,
	levelCode: 'plot_328A'
  },{
	levelName: 'plant',
	levelOrder: 2,
	levelCode: '223'
  },{
	levelName: 'block',
	levelOrder: 0,
	levelCode: '1'
  }
]
```

**Comment by cpommier** [comment]
@cpommier Check this with Ephesis code

**Comment by jeback1** [comment]
Would the proposed schema support multiple values at the same level? E.g.:
observationUnit.observationLevels: [
  {
	levelName: 'plot',
	levelOrder: 1,
	levelCode: 'plot_328A'
  },{
	levelName: 'plant',
	levelOrder: 2,
	levelCode: '223'
  },{
	levelName: 'timePoint',
	levelOrder: 2,
	levelCode: 'flowering'
  },{
	levelName: 'block',
	levelOrder: 0,
	levelCode: '1'
  }
]

**Comment by BrapiCoordinatorSelby** [comment]
@jeback1 Technically, yes you could. I don't really like your example because you introduce time when the levels are intended to be spacial dividers. Another example might be
```
[
  {
    levelName: 'block',
    levelOrder: 0,
    levelCode: 'block_1'
  },
  {
    levelName: 'plot',
    levelOrder: 1,
    levelCode: 'plot_328A'
  },{
    levelName: 'sub-block',
    levelOrder: 1,
    levelCode: '223'
  },{
    levelName: 'plant',
    levelOrder: 2,
    levelCode: '328A_23'
  }
]
```
if you defined plots and sub-blocks as the same level, giving the same area of land two different codes.
