### ISSUE TITLE
adding a studyCode to study response and search ?

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#426]
https://github.com/plantbreeding/API/blob/d676187253e952648b68953b2486a66ff75e98e1/Specification/BrAPI-Core/Studies/Schemas/StudyNewRequest.yaml#L87
In https://urgi.versailles.inra.fr/ephesis/ephesis/viewer.do#trialCard/trialId=1354
There is a trialCode aka studyCode (a brapi study is a GnpIS trial): a unique buisness human readible identification.
We would need something like that in BrAPI

**Comment by BrapiCoordinatorSelby** [comment]
What purpose does the Code serve? How is it different from Name?

**Comment by cpommier** [comment]
https://urgi.versailles.inra.fr/ephesis/ephesis/viewer.do#trialCard/trialId=1267

**Comment by BrapiCoordinatorSelby** [comment]
Discussed with a few other groups in the community, accepted as a general potential need.
