### ISSUE TITLE
Need to search germplasm by taxon, species, collections, ...

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#427]
https://github.com/plantbreeding/API/blob/d676187253e952648b68953b2486a66ff75e98e1/Specification/Components/Schemas/SearchRequestSchemas/SearchRequestParametersGermplasm.yaml#L22
Need to be able to search by the arameters in : https://github.com/plantbreeding/API/blob/d676187253e952648b68953b2486a66ff75e98e1/Specification/BrAPI-Germplasm/Germplasm/Schemas/GermplasmSearchRequest.yaml

**Comment by BrapiCoordinatorSelby** [comment]
For clarification, 

- **SearchRequestParametersGermplasm.yaml** defines the search parameters for other objects (ie Studies, ObsUnits, etc) to search by germplasmDbId and germplasmName
- **GermplasmSearchRequest.yaml** defines the search parameters for finding a Germplasm

Is this still an issue?

**Comment by cpommier** [comment]
Discussion With Peter. The field we are requesting (species, genus, germplasmSynonyms, etc...) are not present in the Study or ObservationUnit JSON. So there is no possibility for us to filter directly by those in FAIDARE/ephesis. In fact it is implicitly a two step process: autocomplete on germplasm name or synonyme in accession field, get the list of germplasmDbId then do a study/observationUnit serach by germplasmDbId.

**Comment by cpommier** [comment]
Ok ?
