### ISSUE TITLE
Grouping germplasm by collection/panel/population

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#429]
https://github.com/plantbreeding/API/blob/d676187253e952648b68953b2486a66ff75e98e1/Specification/BrAPI-Germplasm/Germplasm/Schemas/GermplasmNewRequest.yaml#L6

We are using in FAIDARE a search by panel/collection/population What about adding such a filed in germplasm and germplasm search ?

**Comment by BrapiCoordinatorSelby** [comment]
Add 'collection' string to germplasm
