### ISSUE TITLE
GET data from multiple studies simultaneously

### ISSUE THREAD

**Issue by mverouden** [plantbreeding/API#44]
The GET call [[/brapi/v1/studies/{studyDbId}/table]](https://github.com/plantbreeding/API/blob/master/Specification/Studies/StudyObservationUnitsAsTable.md) allows for extraction of field data based on a studyDbId.

In Ithaca the concept of a study was redefined. In the current definition a trial can contain multiple studies. 

This means that to fetch all field data for a trial several calls have to made. Can a specification be added to brapi e.g. [/brapi/v1/trials/{trialDbId}/table] that fetches all field data for a trial in one call? This function would have the same functionality as the previous definition of [/brapi/v1/studies/{studyDbId}/table] prior to the introduction of a trial containing multiple studies.

The call [/brapi/v1/studies/{studyDbId}/table] would still be very useful if you would like to fetch field data for a specific study.

**Comment by lukasmueller** [comment]
Yes, this is a great suggestions. I would propose to add this in version 2, what do you think? I add a milestone version 2 for now.

**Comment by cpommier** [comment]
See also 
export phenotype-search result as table/csv #191
https://github.com/plantbreeding/API/issues/191
