### ISSUE TITLE
Errors about 'BaseValidate' does not exist in the current context 

### ISSUE THREAD

**Issue by meisongdai** [plantbreeding/API#452]
On compiling the project I get many errors:

Error	CS0103	The name 'BaseValidate' does not exist in the current context

**Comment by BrapiCoordinatorSelby** [comment]
Hi @meisongdai 
Can you please add some more detail about what you were trying to do?
This repository is only documentation written in YAML, along with some Python scripts for manipulating that YAML. There is nothing to be compiled here.

**Comment by BrapiCoordinatorSelby** [comment]
Closed due to inactivity
