### ISSUE TITLE
Trait is not updated in PUT /variables

### ISSUE THREAD

**Issue by ctucker3** [plantbreeding/API#455]
When you `PUT /variables` and include the trait id, the trait is not updated to the values set in the request body. 

Simple example: 

```
{
  "synonyms": ["t3", "t4"],
  "trait": {
	  "traitDbId": "4c81bc62-dc5d-4436-ad3d-cdb783340645",
	  "entity": "Plant",
	  "synonyms": ["t3", "t4"]
  }
}
```

The trait entity and trait synonyms will not be updated with the request above.

**Comment by dauglyon** [comment]
@ctucker3 is this an issue with a specific endpoint, or a request to add a requirement for such behavior to the specification?

**Comment by BrapiCoordinatorSelby** [comment]
lol good question, from when we were talking earlier I assume it is the former.
@ctucker3 can you move this over here: https://github.com/plantbreeding/brapi-Java-TestServer/issues

**Comment by ctucker3** [comment]
Ah yep, sorry, mixed the two up, thanks!
