### ISSUE TITLE
propose renaming SaveOrUpdateObservationUnits.md

### ISSUE THREAD

**Issue by mverouden** [plantbreeding/API#46]
I propose to rename API/Specification/Studies/SaveOrUpdateObservationUnits.md to API/Specification/Studies/ObservationUnitsSaveOrUpdate.md to get a better sorting in GITHUB in case this POST call is linked to API/Specification/Studies/ObservationUnitDetails.md.

It has been done for API/Specification/Studies/StudyObservationUnitsAsTable.md and  API/Specification/Studies/StudyObservationUnitsAsTableSave.md.

**Comment by lukasmueller** [comment]
I think that the order is given in the script that assembles the GitHub.com repos. I can move it in there so that it appears after the ObservationUntiDetails.md file?

**Comment by barrow-wight** [comment]
There are two issues - the visible ordering is one. The other, possibly
more important for someone trying to get a handle on the API, relates to
consistency in API call naming.
