### ISSUE TITLE
Near-Infrared Spectroscopy and Other High Dimensional Phenotypic Data

### ISSUE THREAD

**Issue by nickmorales** [plantbreeding/API#469]
It would be interesting to allow for transferring high-dimensional phenotypic data, such as NIRS, Transcriptomics, Metabolomics, or Ground Penetrating Radar, through BrAPI.

We have implemented a common storage solution for these types of data and would like to create a BrAPI endpoint for querying.

**Comment by dlebauer** [comment]
curious why this is closed - can (some of) these sensor based use cases leverage the /images endpoint?

**Comment by BrapiCoordinatorSelby** [comment]
It was an accidental duplicate of #470 
We are working on a proposal for adding NIRS and other types of data to the spec. It will follow a pattern very similar to the image endpoints.
