### ISSUE TITLE
Pagination doesn't work on people call

### ISSUE THREAD

**Issue by ktotam1** [plantbreeding/API#478]
Can't access page 2 of a people GET

**Comment by BrapiCoordinatorSelby** [comment]
@ktotam1 Thanks for your issue

Can you please provide a little bit more detail. Which server are you trying to connect to? What is the full URL that is causing the issue and which parameters are you using? What client application or programing language are you using? This information will help me direct your issue to the right people.

**Comment by ktotam1** [comment]
Hello, I seemed to have posted this on the wrong repo. I will post on breedbase instead
