### ISSUE TITLE
How to assign observationVariables to studies?

### ISSUE THREAD

**Issue by mcrimi** [plantbreeding/API#482]
Hi @BrapiCoordinatorSelby ,

We are working of study data exchange via BrAPI and I was wondering if there would be a way to assign an `observationVariable` to a `studyDbId` , without the need of an observation.

The (simplified) use case is the following:

1) Instance A creates study 1 and POSTs the study to Instance B to do the data collection
2) Instance B receives the study a1 with all the information needed for data collection, including traits to be collected. When data collection is finished, Instance B then POSTs the observations back into instance A.

cc: @nahuel-soldevilla @jframi @abatac

**Comment by BrapiCoordinatorSelby** [comment]
Hi @mcrimi 
I remember talking about this with other teams, but I think you are the first to open an official issue for it, thank you.
I agree this is a gap in the specification. Unless there are alternative suggestions, I will resolve this by adding `studyDbId` and `studyName` to the `observationVariable` object spec.

**Comment by mcrimi** [comment]
Hi @BrapiCoordinatorSelby. That sounds very good, thank you very much for your quick response.

**Comment by mverouden** [comment]
@mcrimi Keep in mind, that this will not be done immediately. It is now marked for v2.1. Therefore, it will also not be present in any implementation of the v2.0 specs.

**Comment by mcrimi** [comment]
Thanks @mverouden, yes, that's what I had assumed. One consideration that I'm sure you're considering already @BrapiCoordinatorSelby is that a given `observationVariable` can be assigned to multiple `studyDBid`.

**Comment by BrapiCoordinatorSelby** [comment]
That is an excellent point I had not considered, thanks!
So it should be `"studyDbIds: ["id1", "id2"]` as an array of connected studies. That should allow you to assign a variable to one or more studies. And `GET /variables?studyDbId=id1` is already available, so you can retrieve all the variables for a given study.

**Comment by abatac** [comment]
Another alternative is to add `observationVariableDbIds: [string]` in `PUT /studies/{studyDbId}`, so that it's clear that the system is assigning observation variables to the study. Rather than in `PUT /variables/{observationVariablesDbId}` which is the main objective is to edit the variable.

@BrapiCoordinatorSelby @nahuel-soldevilla @mcrimi

**Comment by abatac** [comment]
> Another alternative is to add `observationVariableDbIds: [string]` in `PUT /studies/{studyDbId}`, so that it's clear that the system is assigning observation variables to the study. Rather than in `PUT /variables/{observationVariablesDbId}` which is the main objective is to edit the variable.
> 
> @BrapiCoordinatorSelby @nahuel-soldevilla @mcrimi

Is it OK to include this in v2.1? @BrapiCoordinatorSelby
