### ISSUE TITLE
Expand locations to include location hierarchies

### ISSUE THREAD

**Issue by bellerbrock** [plantbreeding/API#489]
It would be useful to be able to handle multiple levels of location in BrAPI. The existing locations call is good for managing locations at the highest level, for example research stations. But for many breeding activities it's also necessary to manage data at a finer level, like specific fields on the research station. 

For example weather data may be related to location at the research station level, but then at the field level a breeder might track data like soil type and previous crop rotation. And of course the specific field location is needed to actually locate the study in person.

One way to implementing it could be adding a concept of sublocation, with locations comprising of multiple sublocations just like trials are comprised of multiple studies. By using a generic term like sublocation it could be used to represent not just a field on a research station but also a specific rack in a storage location or a bench in a greenhouse, etc. 

A sublocation search by location ID could look something like this:

```GET https://sweetpotatobase.org/brapi/v2/sublocations?locationDbId=133```
```
{
    "result": {
        "data": [
            {
              "locationDbId": "133",
              "locationName": "Sandhills Research Station",
              "sublocationDbId": "1032",
              "sublocationName": "Field A2",
              "additionalInfo" : {
                "acreage": 3.43,
                "primarySoil": "Blanton",
                "crop2020": "Corn",
                "crop2019": "Soy",
                "crop2018": "Sweetpotato",
                ...
              }
             ...
            },
            {
              "locationDbId": "133",
              "locationName": "Sandhills Research Station",
              "sublocationDbId": "1033",
              "sublocationName": "Field A3",
              "additionalInfo" : {
                "acreage": 2.78,
                "primarySoil": "Blanton",
                "crop2020": "Sweetpotato",
                "crop2019": "Corn",
                "crop2018": "Soy",
                ...
              }
             ...
            },
            ...
            {
              "locationDbId": "133",
              "locationName": "Sandhills Research Station",
              "sublocationDbId": "1140",
              "sublocationName": "Field F5C",
              "additionalInfo" : {
                "acreage": 0.4,
                "primarySoil": "Toisnot",
                "crop2020": "Soy",
                "crop2019": "Sweetpotato",
                "crop2018": "Corn",
                ...
              }
             ...
            }
        ]
    }
}
```

For context here's an example map from a station that breeds sweetpotatoes:

![SandhillsStationMap2016](https://user-images.githubusercontent.com/11297346/136443859-54b8b3b6-4693-4250-b94b-010fd96c213a.jpg)

**Comment by BrapiCoordinatorSelby** [comment]
Could the same thing be achieved by adding the fields `parentLocationDbId` and `parentLocationName` to the existing Location entity? with the ability to filter/search by parent location?

**Comment by bellerbrock** [comment]
@BrapiCoordinatorSelby I like that idea. Keeps it simple, and should be all that is necessary manage hierarchies.

**Comment by BrapiCoordinatorSelby** [comment]
in BrAPI V2.1, to retrieve sub-locations for the location "133" use the query `GET /locations?parentLocationDbId=133`
