### ISSUE TITLE
New endpoint to update genotyping data

### ISSUE THREAD

**Issue by aliceboizet** [plantbreeding/API#491]
We would need this new endpoint PUT variantSets/{variantSetDbId}/calls to update some calls

According to the new genotyping response structure, the request body could look like:
```json
{
    "variants": ["variant1","variant2"],
    "callSets": ["callSet1","callSet2"],
    "genotypes": [
        ["A","G"],
        ["A","T"]
    ]
}
```

**Comment by BrapiCoordinatorSelby** [comment]
Related to #451
