### ISSUE TITLE
Genome Map Details brapi/v1/maps/{mapDbId} response object

### ISSUE THREAD

**Issue by c5sire** [plantbreeding/API#50]
Should the inner array in results rather be 'data' instead of linkageGroups?

**Comment by BrapiCoordinatorSelby** [comment]
The 'linkageGroups' field seems to be representing linkage group summaries, and this call is not currently paged. 
Does anyone know a possible upper bound for the number of linkage group summaries you could have in a genome map object?
if that number is "small" (less than 20?) then I would suggest we leave this call the way it is. If you could potentially have a "Large" (more than 20?) number of linkage group summaries, then I would suggest making a new call /maps/{mapDbId}/linkagegroups and give that call pagination.
