### ISSUE TITLE
Date format all API

### ISSUE THREAD

**Issue by gcornut** [plantbreeding/API#52]
We should use the [ISO 8601](https://wikipedia.org/wiki/ISO_8601) date/time format across all API calls.
We should also **enforce timezones** for every date.
Example: `"2017-01-19T23:23:41+01:00"` => Jan 19th 2017 at 11:23:41 pm (UTC+1)

Related call:
- study (star, end dates)
- phenotype (observationTimestamp)
- sample (sample date)
- etc.

**Comment by rfinkers** [comment]
+1

**Comment by cpommier** [comment]
+1
