### ISSUE TITLE
http://docs.brapi.apiary.io/ pages don't allow cut and paste

### ISSUE THREAD

**Issue by TimeScience** [plantbreeding/API#54]
Hi All, On my browser (windows laptop with chrome) there is no way to cut/paste any text/code from the Brapi page. it just treats it as a touch event and tries to scroll the page. 

For a code documentation site this makes things very hard to use. because you can't actually copy any of the codes or example text. Likewise if you want to say, send people the URL with some text copied from the intro so they know what the project is about, there is no way to do that.

Update: I tracked the problem further and it seems to happen only in Chrome on PC's with touchscreen. I've tried it on two touchsceen enabled laptops and you can't select, 2 other machines that aren't touch enabled don't have the problem. No problem for any machines with firefox.  

So maybe a small issue but you might want to tell the Apiary people because it makes the site pretty unusable for those of us who do have touchscreen laptops. 

Tim

**Comment by lukasmueller** [comment]
Hi Tim,

I never had this problem, but then I have not used a touchscreen laptop :-)

Not sure what to do about this, I think even on a touchscreen laptop you can just use the trackpad and you will be fine.

cheers
Lukas

**Comment by TimeScience** [comment]
I suspect it is an Apiary/Chrome bug so not directly your problem, but I
don't have an apiary account so I couldn't post it to them

re touchpad... I am using a mouse but I can't select anything. I assume the
'touch' and 'click' events are getting mixed up somehow since it only
occurred on the two touchscreen laptops and not in firefox.

--
​
Tim Brown
Research Fellow, Center for Plant Energy Biology
Australian National University, Research School of Biology, Canberra ACT
0200
*bit.ly/Tim_ANU <http://bit.ly/Tim_ANU>* | tim.brown@anu.edu.au
​
+61 0419-006-102
​ (m) |
​
Skype: *TimeScience*
