### ISSUE TITLE
New call to update the Plot Layout 

### ISSUE THREAD

**Issue by ejbriones** [plantbreeding/API#61]
**To update  Plot layout: 
**PUT brapi/v2/studies/studyDbId/layout****

{
  "metadata": {
    "pagination": {
      "pageSize": 0,
      "currentPage": 0,
      "totalCount": 0,
      "totalPages": 0
    }
  },
  "result": {
    "data": [
      {
        "studyDbId": 1,
        "observationUnitDbId": 11,
        "X": 20,
        "Y": 22
      }
     
    ]
  }
}

**Comment by BrapiCoordinatorSelby** [comment]
Layout doesn't seem to be clearly defined. Is a layout part of a Study or an Observation Unit? or can it be both depending on the circumstances?
Are X and Y the only fields relevant to a Layout object? 
It seems like Layout is just a subset of Observation Unit fields, would we consider making it a distinct sub object?

This would be my suggestion:
GET /studies/{studyDbId}/layouts
 -> All layouts in that study (convenience method)
GET /studies/{studyDbId}/observationunits/{observationunitDbId}/layouts
 -> The layout for and observation unit
PUT /studies/{studyDbId}/observationunits/{observationunitDbId}/layouts
 -> Update the layout for a given observation unit

This is the most RESTful way, without giving each layout its own DbId (which I think is unnecessary). The Keys for a PUT should go in the URL not the object body. This allows for distinct paths for add vs update. 

If its really important to update a list of layout all at once, we can add the method @ejbriones has outlined above, but I would consider making it a POST. You are POSTing a list of layouts to the server and its up for the server implementation to read the DbIds out of the object and determine what to do with each layout. 

Thoughts?

**Comment by BrapiCoordinatorSelby** [comment]
After a quick lesson from @nickmorales, I think I understand the basics of layouts (thanks Nick), and why @ejbriones proposal makes sense. 
I'll write it up!
