### ISSUE TITLE
Add call for Breeding Methods

### ISSUE THREAD

**Issue by j-alberto** [plantbreeding/API#62]
GET /brapi/v2/breedingMethods

{
  "metadata": {
    "pagination": {
      "pageNumber": 1,
      "pageSize": 2,
      "totalCount": 100,
      "totalPages": 50
    },
    "status": [],
    "datafiles": []
  },
  "result": {
    "data": [
           {
            "breedingMethodDbId": 9,
            "abbreviation": "MBCR",
            "name": "Male Backcross",
            "description": "Backcross to recover a specific gene. The coding in the genealogical table records which parent was used as the male in each cycle. Each entity kept separate."
        },
        {
            "breedingMethodDbId": 10,
            "abbreviation": "DSP",
            "name": "Single plant selection",
            "description": "Derivation through selection of a single plant, inflorescence, fruit or seed from a population"
        }
    ]
  }
}

**Comment by BrapiCoordinatorSelby** [comment]
@j-alberto Can you please outline a use case which requires this call?
Is a BreedingMethod object connected to any of the other entities in BrAPI? Study? Germplasm? Pedigree?

**Comment by BrapiCoordinatorSelby** [comment]
@jeback1 @lukasmueller @j-alberto 
Is a list of Breeding Methods needed or useful? can anyone answer my questions above?

**Comment by j-alberto** [comment]
It's important to specify by which method a germplasm was produced. A breeding method defines whether it's a generative or derivative germplasm. Breeding methods also define rules for creating names, for example some breeding method codes are used when creating  Selection Histories: 
PTSS02B00073S-0Y-0B-0Y-0B-4Y-0ZTB-0SY
PTSS02B00071S-0Y-0B-0Y-0B
CDSS96B00658T-0TOPY-2M-0Y-0M-0Y-0B-3Y-0B

Also for pedigrees where the selection history is included, breeding methods determine how their pedigree is created
[HWSA(FG)C1-4-2-B/CML444//NAW-48-2-1]-B-3-2-1-1-BBB

So any system trying to generate such names will need this piece of information.

**Comment by BrapiCoordinatorSelby** [comment]
Thanks @j-alberto!

would it make sense to add "breedingMethodDbId" to the germplasm object as well as this new call? I want to keep all the objects connected. If they don't easily connect, it tells me there might be an object model missing somewhere.

Is it possible for a germplasm to have multiple breeding methods? (pardon my ignorance, I'm guessing this answer is No but it doesn't hurt to ask)

**Comment by j-alberto** [comment]
Yeah, it makes all sense to include breedingMethodDbId in germplasm model as is integral part of genealogy data models such as GMS.

In strict sense, a germplasm can just have one method. Adittionally, very time a selection or a regeneration is made a different method could be used, although that would be considered new germplasm.
