### ISSUE TITLE
indicating progress of async exports

### ISSUE THREAD

**Issue by GuilhemSempere** [plantbreeding/API#79]
It was defined that /allelematrix-search/status/{extractId} would respond something like

{ "metadata": { "pagination": { "pageSize": 0, "currentPage": 0, "totalCount": 0, "totalPages": 0 }, "status": [{"code" : "asynchstatus" , "message" : "FINISHED"}], "datafiles": ["/shared_files/app_test/file_bundle/crops/rice/extract/output/721"] }, "result" : { "data": [] } }

I would like to suggest adding an optional asynchprogress key to the status object, in order to provide means for implementations to supply some info, as a string, about the progress of the export process.

**Comment by BrapiCoordinatorSelby** [comment]
#146
