### ISSUE TITLE
Security concern: using URI as path identifier for BrAPI entities

### ISSUE THREAD

**Issue by gcornut** [plantbreeding/API#85]
Hello everyone,

I have been implementing the Breeding API with an information system where study identifiers or germplasm identifiers are URIs. 

So when implementing `/brapi/v1/germplasm/{URI}`, I tried simply encoding the URIs using the standard URL encode: `/brapi/v1/germplasm/https%3A%2F%2Fdoi.org%2F10.15454%2F1.4489666216568333E12`

This however did not work as Apache Tomcat as a security constraint that disallows the use of encoded slashes in URL path. This behavior is controlled by a parameter named `ALLOW_ENCODED_SLASH` and set to `false` for security reasons.

From the official Apache Tomcat [documentation](http://tomcat.apache.org/tomcat-7.0-doc/security-howto.html):
"
The **org.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH** system properties allow non-standard parsing of the request URI.
Using these options when behind a reverse proxy may enable an attacker to bypass any security constraints enforced by the proxy.
"

This security concern might apply to other types of HTTP server but does not apply to query parameters (`/url?param={URI}`) or JSON POST object (`{"germplasmDbIds":"{URI}"}`)

The use of URIs as path identifiers may not be a common use case for the Breeding API but we have at least two partners would use URIs with us. **Does anyone have this use case?**

I would suggest **we document a special case for using URIs in BrAPI paths**.

We could, for example, use a double URL encoding prefixed with "`uri:`". 
Example: `/brapi/v1/germplasm/uri:https%253A%252F%252Fdoi.org%252F10.15454%252F1.4489666216568333E12`

This way, the server knows how extract the actual identifier from the URL.
Example:
```
original:           uri:https%253A%252F%252Fdoi.org%252F10.15454%252F1.4489666216568333E1
removing preffix:   https%253A%252F%252Fdoi.org%252F10.15454%252F1.4489666216568333E1
first URL decode:   https%3A%2F%2Fdoi.org%2F10.15454%2F1.4489666216568333E12
second URL decode:  https://doi.org/10.15454/1.4489666216568333E12
```

Don't hesitate if you have other ideas

**Comment by netbofia** [comment]
Not quite sure it this is a simple solution but I would suggest using hashes base64, md5. sha1 etc.

since url encode also requires some work to do manually opting for hashes might be a more elegant solution. 
    brapi/v1/germplasm/851918d98e94799a60c518ed17d33e6d
          or
    brapi/v1/germplasm/?uri=851918d98e94799a60c518ed17d33e6d

**Comment by gcornut** [comment]
Yeah I though of hashes but sha1 and md5 are not reversable and base 64 produces big hashes :/

Anyway, we started using doubly encoded URI (without "uri:" preffix):
```/brapi/v1/germplasm/https%253A%252F%252Fdoi.org%252F10.15454%252F1.4489666216568333E1```
It does the trick for now.

We actually also consider forcing Tomcat to allow encoded slashes because the security concern might not apply in our case.

In the end this issue might only be relevant to us so we don't need documentation on that in the API. 
But at least if any one has this kind of problem, they can refer to this github issue. 

Thanks for the help @netbofia. I'm closing the issue
