### ISSUE TITLE
Inconsistent returned data type for /studies/{dbId}/observationVariables

### ISSUE THREAD

**Issue by gcornut** [plantbreeding/API#9]
The observation variables listed in `/brapi/v1/studies/{dbId}/observationVariables` don't have the same returned value as `/brapi/v1/variables`, `/brapi/v1/variables/{dbId}` or `/brapi/v1/variables-search`

I'm opening a pull request

**Comment by lukasmueller** [comment]
fixed in merge,  d407f2663aad6c2984ea278b42413da09d709a0d
