### ISSUE TITLE
germplasm/id call internal database id  | What to do if no id is given?

### ISSUE THREAD

**Issue by netbofia** [plantbreeding/API#90]
Hello,

For the [germplasm/{id} call](https://github.com/plantbreeding/API/blob/master/Specification/Germplasm/GermplasmDetailsByGermplasmDbId.md)

id (required, string, 382) ... germplasmDbId - the internal id of the germplasm

In parameters it's specified that ID is required what is the default response if no id is specified? 
Error or the first 1000 germplasm?

Bruno

**Comment by gcornut** [comment]
Well the identifier({id}) is a path parameter so if you don't specify it, you are requesting 'germplasm/' which is an other URL that does not correspond to BrAPI call so you should return a 404.

Most of the other BrAPI object have both detail call (object/{id}) and list call (object/). So for them if you omit the identifier you get the list of objects.

Maybe we should consider adding germplasm list in v2. I think more consistency across the API would be a good thing

**Comment by netbofia** [comment]
Yes I noticed that afterwards. Essentially germplasm-search already lists all germplasm. 
/germplasm-search might make more sense as /germplasm in v2. Unless /germplasm was used to list all germplasms with less attributes just ids and names.
