### ISSUE TITLE
observationTimestamp is not not applicable in /brapi/v1/studies/{studyDbId}/table]

### ISSUE THREAD

**Issue by nikkicarumba** [plantbreeding/API#91]
observationTimestamp can be different for each observation variable. I would like to suggest to remove it.

**Comment by BrapiCoordinatorSelby** [comment]
I believe the intention behind this call is to present a table of Observations Units. Each Observation Unit should be tied to 1 observation variable and 1 timestamp. So in this table you could list out all the different observations with their distinct variables and timestamps.

Please correct me if I'm missing something. There is not much documentation around this explaining exactly what the output should be.

**Comment by BrapiCoordinatorSelby** [comment]
Wow I did not understand what I was talking about in November hahaha 
@nikkicarumba you are absolutely correct. ObservationTimeStamp does not make sense in the table. Each row of the table contains multiple observations, so a time stamp is meaningless.
