### ISSUE TITLE
List Trial Summaries GET call

### ISSUE THREAD

**Issue by mverouden** [plantbreeding/API#98]
How should the List Trial Summaries GET call be specified? This part is missing in the specification, if I match it with the Program List GET call (/brapi/v1/programs) I assume it to look something like this:
/brapi/v1/trials?programDbId={programDbId}&locationDbId={locationDbId}&pageSize={pageSize}&page={page}&active={active}&sortBy={sortBy}&sortOrder={sortOrder}

Please also add this to specification when correct as well as to the apiary.

Thanks in advance,

**Comment by lukasmueller** [comment]
I would argue that we could also provide the observationVariableName right away in addition to the DbId, because that would have to be looked up in almost any case.
